DataRecce/recce

README.md

Update document
- Update README wording
- Add Badges into README
N/A
N/A

[Refactor] Update README wording and add badges

---

README.md

Update document
Fix typo
N/A
N/A

[Fix] Fix typo

---

js/.eslintrc.json
js/.prettierrc
js/app/page.tsx
js/src/lib/api/useVersion.ts
recce/server.py

enhancement
display version on the page
none
----
show version on the top right

[Chore] Add version number

---

recce/dbt.py

bugfix
make it compatible to old dbt versions
nope

[Bug] handle lost on_configuration_change field

---

.gitignore
Makefile
recce/dbt.py
setup.py
tests/test_dbt.py
tests/test_sql_generator.py
tox.ini

bugfix
make it compatible with dbt-core at least 1.5

[Bug] dbt compatible

---

js/src/components/lineage/LineageView.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/schema/SqlDiffView.tsx

Feature
- Add a button to show raw code diff when detecting a modified model
RC-38
NONE

[Feature] Add sql diff view when navigating a modified model

---

js/package.json
js/pnpm-lock.yaml
js/src/components/lineage/LineageView.tsx

Feature
- Upgrade ReactFlow package to v11.10
- Change icon of siwtch mode
- Add dowload image button in Lineage View
Example:
RC-45

[Feature] rc-45 Add download image button in Lineage View

---

js/src/components/lineage/LineageView.tsx

Bugfix
- Mark the correct color in minimap based on the changed status
N/A

[Fix] Lineage minimap color

---

recce/cli.py
recce/dbt.py
recce/server.py

Feature
- Support `--target`, `--profile`, `--project-dir` and `--profiles-dir` options
#26 

[Feature] Suport dbt's target and profile related options

---

js/src/lib/const.ts

Bugfix
- Fix PUBLIC_API_URL get a wrong URL in dev environmnet
N/A

[Fix] PUBLIC_API_URL issue

---

recce/server.py

[Chore] Make python 3.9 works

---

.gitignore
recce/cli.py
recce/dbt.py
recce/server.py

feature added
parts of `column mismatched` feature
rc-47
---
We added
* a cli command for demo `compare_column_values` (might be removed later)
* api endpoint for `compare_column_values`
Frontend will be implemented later.
```
$ recce compare-all-columns customer_id customers
column_name  perfect_match  null_in_a  null_in_b  missing_from_a  missing_from_b  conflicting_values
0              CUSTOMER_ID            100          0          0               0               0                   0
1  CUSTOMER_LIFETIME_VALUE             73         52         38               0               0                  27
2               FIRST_NAME            100          0          0 …
```

[Feature] support /api/compare_column_values

---

js/.prettierrc
js/src/components/lineage/MismatchSummary.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/schema/SchemaView.tsx
playground.py
recce/cli.py
recce/dbt.py
recce/server.py

feature added
show mismatched amounts and percentages in a model
rc-47
---

[Feature] Columns mismatched summary

---

recce/apis/__init__.py
recce/apis/check_api.py
recce/apis/db.py
recce/apis/run_api.py
recce/apis/run_func.py
recce/apis/types.py
recce/server.py

Feature
- checklist create and update API
rc-46
NONE

[Feature] Add checklist backend

---

recce/dbt.py

Bugfix
- Fix package_config_from_data function call issue
RC-74

[Bug] rc-74 fix package_config_from_data function call issue

---

js/src/components/lineage/NodeView.tsx
recce/dbt.py

[Bug] Fix bugs on execution and display

---

js/src/components/check/CheckBreadcrumb.tsx
js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx
js/src/components/query/QueryDiffDataGrid.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/SqlEditor.tsx
js/src/lib/api/cacheKeys.ts
js/src/lib/api/checks.ts
js/src/lib/api/runs.ts
recce/apis/check_api.py
recce/apis/run_api.py
recce/apis/types.py

FE Integrate run&check API
Support check delete

[Feature] Frontend Integrates the run and check API

---

js/app/page.tsx

[Chore] make pnpm lint pass

---

js/app/page.tsx
js/src/lib/hooks/useHashLocation.ts

It will show nothing for the index page. Add the default routing.

[Chore] Add default route for index page

---

js/app/page.tsx
js/src/components/lineage/LineageView.tsx
js/src/lib/api/cacheKeys.ts
js/src/lib/api/lineage.ts
js/src/lib/hooks/LineageGraphContext.tsx

1. Cache the result.
1. Make the summary page not empty if lineage data has not been loaded.
rc-82

[Chore] Use useQuery to fetch lineage data

---

js/src/components/summary/SchemaSummary.tsx

Feature
Scheam Summary doesn't include add/remove models
RC-79

[Feature] rc-79 Schema summary doesn't include add/remove models

---

.github/workflows/eslint.yaml
.github/workflows/flake8.yaml
recce/dbt.py

Chore
- Add code lint in for CI
NA
NONE

[Chore] Add code lint workflow

---

js/.editorconfig
js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx
js/src/components/check/SchemaDiffView.tsx
js/src/components/lineage/MismatchSummary.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/query/QueryPage.tsx
js/src/lib/api/checks.ts
js/src/lib/api/runs.ts
recce/apis/check_api.py
recce/apis/types.py

Feature
- Implement the schema check in backend
- Implement the schema check in CheckDetail View
RC-68

[Feature] rc-68 allow to create a schema check

---

js/src/lib/api/checks.ts
recce/apis/check_api.py

- add `params` as an object
- move `node_id` under `params`
Fix
- Refine the create check API input format
RC-68

[Refine] modify create check api input format

---

js/src/components/lineage/NodeView.tsx
recce/apis/run_api.py

[Feature] Make the value diff available all models

---

js/src/components/check/CheckPage.tsx
js/src/lib/hooks/useHashLocation.ts

[Bug] Fix the new added check is not selected by default

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx
js/src/components/check/QueryView.tsx
js/src/components/check/ValueDiffView.tsx
js/src/components/lineage/MismatchSummary.tsx
js/src/components/query/QueryDataGrid.tsx
js/src/components/query/QueryDiffDataGrid.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/querydiff.test.ts
js/src/components/query/querydiff.tsx
js/src/components/query/styles.css
js/src/lib/api/adhocQuery.ts
js/src/lib/api/checks.ts
js/src/lib/api/runs.ts
js/src/lib/api/types.ts
js/src/lib/api/valuediff.ts
js/src/lib/hooks/useHashLocation.ts
recce/apis/check_api.py
recce/apis/run_func.py
recce/apis/types.py

1. Run adhoc query
2. Add to checklist

[Feature] Allows to add adhoc query to check

---

js/src/components/check/ValueDiffView.tsx
js/src/components/lineage/MismatchSummary.tsx
js/src/lib/api/adhocQuery.ts
js/src/lib/api/valuediff.ts
recce/dbt.py

enhancement
value-diff must choose a primary key to compare data, we show the validation errors to invalid primary key.
a valid primary key must be:
* unique
* not null
rc-92

[Feature] validate Primary Key for value-diff

---

js/src/components/check/ValueDiffView.tsx
recce/dbt.py

enhancement
show packages not installed errors
rc-92
---

[Feature] Warning packages not installed

---

js/src/components/check/QueryDiffView.tsx
js/src/components/check/QueryView.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/SqlEditor.tsx

-I n ad-hoc query as check, the SQL used to query should be shown.
- Add run and run diff keyboard shortcut
cmd + enter changes to run query. 
cmd + shift + enter is to run diff

Query page enhancement

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx
js/src/components/check/ProfileDiffView.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/lineage/Profile.tsx
js/src/components/lineage/ProfileDataGrid.tsx
js/src/components/lineage/ProfileDiffGrid.tsx
js/src/lib/api/profile.ts
js/src/lib/api/types.ts
recce/apis/check_api.py
recce/apis/run_func.py
recce/apis/types.py
recce/dbt.py

Feature
- allow to profile models and add the result as a check
RC-94
NONE

[Feature] Add profile check

---

js/src/components/check/QueryDiffView.tsx
js/src/components/check/QueryView.tsx
js/src/components/query/QueryDataGrid.tsx
js/src/components/query/QueryDiffDataGrid.tsx
js/src/components/query/QueryPage.tsx
js/src/lib/api/adhocQuery.ts
js/src/lib/api/runs.ts
js/src/lib/api/types.ts
recce/apis/check_api.py
recce/apis/run_api.py
recce/apis/run_func.py
recce/apis/types.py
recce/cli.py
recce/dbt.py
recce/exceptions.py
recce/server.py

Fix #30 
1. Add cancel button in the query result pane
2. Show cancelled if failed

[Feature] Support cancel in the adhoc query page

---

js/src/components/check/CheckPage.tsx

Feature
- have a basic markdown to post a checklist to a PR comment
RC-99
NONE

[Feature] Allows to copy checklist as markdown

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx
js/src/components/check/RowCountDiffView.tsx
js/src/components/lineage/NodeSelector.tsx
js/src/components/lineage/NodeTag.tsx
js/src/components/lineage/NodeView.tsx
js/src/lib/api/checks.ts
js/src/lib/api/types.ts
recce/apis/check_api.py
recce/apis/types.py

Feature
- Support new row count check for single or multiple nodes
RC-90

[Feature] RC-90 Add row count check for single or multiple nodes

---

js/src/components/lineage/Profile.tsx
js/src/lib/api/profile.ts
recce/apis/run_func.py

Chore
- rewrite profile to fit new task architecture
NONE

[Chore] Make profile fit into the new task arch

---

recce/apis/check_func.py
recce/apis/run_api.py

Fix the value diff issue
Fix the add schema check issue.

[Bug] cannot run value diff

---

recce/apis/run_func.py
recce/tasks/__init__.py
recce/tasks/core.py
recce/tasks/profile.py
recce/tasks/query.py
recce/tasks/valuediff.py

1. Rename executor to task
2. Put to a separate package.

[Chore] Rename executor to task

---

js/src/components/lineage/LineageView.tsx

Bug
- Show no change found and let users to switch to all nodes mode
RC-81
NONE

[Bug] Show hint if there is no change found

---

js/src/components/lineage/NodeView.tsx
js/src/components/lineage/Profile.tsx
js/src/components/lineage/ProfileDiffGrid.tsx
recce/dbt.py

Feature
- show error when profile failed
- allow to cancel profile task
- fix cannot visualize profile result in snowflake 
- fix cannot visualize boolean value of profile result in data grid
RC-104
NONE

[Feature] Fix and enhance profile task

---

js/src/components/check/ProfileDiffView.tsx
js/src/components/check/QueryDiffView.tsx
js/src/components/check/QueryView.tsx
js/src/components/check/RowCountDiffView.tsx
js/src/components/check/SchemaDiffView.tsx
js/src/components/check/ValueDiffView.tsx
js/src/components/lineage/ProfileDiffGrid.tsx
js/src/components/query/QueryDataGrid.tsx
js/src/components/query/QueryDiffDataGrid.tsx
js/src/components/schema/SchemaView.tsx
js/src/components/screenshot/ScreenshotBox.tsx

[Feature] Screenshot box example

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/ProfileDiffView.tsx
js/src/components/check/QueryDiffView.tsx
js/src/components/check/QueryView.tsx
js/src/components/check/RowCountDiffView.tsx
js/src/components/check/SchemaDiffView.tsx
js/src/components/check/ValueDiffView.tsx
js/src/components/data-grid/ScreenshotDataGrid.tsx
js/src/components/lineage/ProfileDiffGrid.tsx
js/src/components/query/QueryDataGrid.tsx
js/src/components/query/QueryDiffDataGrid.tsx
js/src/components/query/QueryPage.tsx
js/src/components/schema/SchemaView.tsx
js/src/components/screenshot/ScreenshotBox.tsx
js/src/lib/hooks/ScreenShot.tsx

Feature
- Save query diff result as an image
- Save the image into clipboard
- Highlight the copied area when mouse hover the copy button
RC-93

[Feature] Copy the query diff result as image and save to clipboard

---

recce/cli.py

Hide the `recce query` and `recce summary` because we now focus on Web UI rather than CLI. 
Chore

[Chore] Hide the query and diff cli command

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckPage.tsx

Bug
- Clipboard API works only under HTTPS, we need another way to do it.
RC-114
NONE

[Bug] Copy checklist under HTTP

---

js/src/components/schema/SchemaView.tsx

Bugfix
Schema view only show copy button at checklist page
rc-93

[Bug] rc-93 Schema view only show copy button at checklist page

---

js/src/components/lineage/ProfileDiffGrid.tsx

`diff-cell` -> `diff-cell-modified`

[Bug] Profile diff use wrong class name

---

js/app/page.tsx
js/src/components/check/ValueDiffView.tsx
js/src/components/lineage/ProfileDiffGrid.tsx

Feature & bugfix
- Remove summary tab
- Fix copy to clipboard button issues
N/A

[Feature] remove summary tab

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckPage.tsx
recce/cli.py

Bug
- change recce server default binding to localhost
- To hint users that copy checklist failed
RC-114
localhost
0.0.0.0
NONE

[Bug] Add error handler for copying checklist 

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckList.tsx
js/src/components/check/CheckPage.tsx
js/src/lib/api/checks.ts
recce/apis/check_api.py

Feature
- allow to reorder check item in checklist
RC-110
NONE

[Feature] Support to reorder the check list

---

js/src/components/lineage/NodeSelector.tsx
js/src/components/lineage/NodeTag.tsx

Bugfix
Fix select mode exit accidentally issue
N/A

[Bug] Fix select mode exit accidentally issue

---

js/src/components/check/RowCountDiffView.tsx

Bugfix
row count check don't show color when still loading
N/A

[Bug] row count check don't show color when still loading

---

js/src/components/lineage/LineageView.tsx

Feature
- copy the lineage view as an image to clipboard
- Result
RC-117

[Feature] rc-117 copy the lineage view as image to clipboard

---

js/src/components/check/RowCountDiffView.tsx
js/src/components/lineage/NodeSelector.tsx
js/src/components/lineage/NodeTag.tsx
js/src/components/lineage/NodeView.tsx
js/src/lib/api/adhocQuery.ts
js/src/lib/api/cacheKeys.ts
js/src/lib/api/checks.ts
js/src/lib/api/models.ts
js/src/lib/hooks/RecceContextProvider.tsx
js/src/lib/hooks/RecceQueryContext.tsx
recce/apis/run_func.py
recce/tasks/__init__.py
recce/tasks/query.py

Featrue
- Refactor query row count by run task framework
Rc-105

[Feature] rc-105 refactor row count query by run task

---

recce/tasks/query.py

Issue a wrong sql, it would show no data instead of the error message.
Bug 

[Bug] The query diff does not show error message correclty

---

README.md
docs/get-started-jaffle-shop.md
recce/apis/check_api.py
recce/apis/db.py
recce/apis/run_api.py
recce/apis/run_func.py
recce/cli.py
recce/dbt.py
recce/event/track.py
recce/models/__init__.py
recce/models/check.py
recce/models/run.py
recce/models/state.py
recce/models/types.py
recce/server.py
tests/models/test_state.py

Allows to run recce server with state file
- Persist the state to `issue-123.json`
```
recce server issue-123.json
```
- No persistence
```
recce server
```

[Feature] support to store the checklist state so that i can switch branch

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx
js/src/components/check/check.ts
js/src/lib/hooks/ScreenShot.tsx
js/src/lib/hooks/useClipBoardToast.tsx

Feature
- If submitters have their own PR template, it's helpful to copy a specific check to patse.
RC-128
NONE

[Feature] Allow to do per-check copy

---

README.md

Update the README. Add the hint to tell the user how to prepare the base envrionments' artifacts

[Document] Add the hint to tell the user how to prepare the base envrionments' artifacts

---

README.md

[Document] Update readme

---

js/src/components/valuediff/ValueDiffResultView.tsx

[Bug] Value diff. Show 0% instead of N/A

---

js/src/components/lineage/LineageView.tsx
js/src/lib/hooks/ScreenShot.tsx

Enhance 
- The lineage view will be copied based on the current view
- Image will include the react flow background and legends
- Example
RC-124

[Feature] rc-124 Improve copy image from lineage view

---

js/src/components/check/CheckDetail.tsx
js/src/components/profile/ProfileDiffResultView.tsx
js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/QueryResultView.tsx
js/src/components/run/RunModal.tsx
js/src/lib/api/adhocQuery.ts
js/src/lib/api/checks.ts
js/src/lib/api/profile.ts
recce/apis/check_api.py
recce/models/types.py

Separate the concepts of the two in a check
- **params**: The default run submiission params  when re-running a check.
- **view_options**: The options to view the check.

[Feature] Add view_options in check api

---

recce/models/run.py

[Big] Fix run list api error

---

js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/lineage.ts
js/src/components/lineage/styles.css

Feature
- Highlight the node when the user clicks it to select the detail view
- Redesign the layout of selected nodes
RC-139

[Feature] rc-139 Highliht the node when click it to select detail view

---

js/src/components/lineage/NodeSelector.tsx
js/src/components/lineage/NodeView.tsx
js/src/lib/api/models.ts

Bugfix
- Fix the issue when adding row count check only works on unqueried models
- Fix the issue when selecting multiple models that contain models that already have row count query results; the check will not include those queried models.
RC-122

[Bug] rc-122 row count check only applies to unqueried models

---

recce/apis/check_api.py

Feature
- make default check name more readable
RC-142
NONE

[Feature] Enhance default check name

---

js/src/components/check/CheckDescription.tsx

Feature
- To enhance updating check description UI
RC-141
NONE

[Feature] Simplify updating check description

---

js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/QueryResultView.tsx
js/src/lib/api/types.ts
recce/dbt.py
recce/tasks/dataframe.py
recce/tasks/query.py

[Feature] querying too much data lets web page hang

---

js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/QueryResultView.tsx

[Feature] querying too much data lets web page hang. Fix layout

---

js/src/components/lineage/lineage.ts
js/src/components/schema/SchemaView.tsx
recce/dbt.py

Bug
- To enhance the warning message to differentiate the scenario of missing `catalog.json` and missing schema information.
RC-146
NONE

[Bug] Add catalog metadata and existence information

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx
js/src/components/rowcount/RowCountDiffView.tsx
js/src/components/run/RunView.tsx
js/src/lib/api/adhocQuery.ts
js/src/lib/api/models.ts
js/src/lib/api/rowcount.ts
js/src/lib/api/runs.ts
js/src/lib/api/types.ts
recce/apis/check_api.py
recce/apis/run_func.py
recce/models/state.py
recce/models/types.py
recce/tasks/profile.py
recce/tasks/valuediff.py

Allows user to rerun a check. Supported check types
- query
- query diff
- value diff
- profile diff
- row count diff
Feature

Support to rerun in the check detail page

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckList.tsx
js/src/components/check/LineageDiffView.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/NodeSelector.tsx
js/src/components/lineage/NodeTag.tsx
js/src/lib/api/checks.ts
js/src/lib/api/types.ts
recce/apis/check_api.py
recce/models/types.py

Feature
- Support lineage diff check
- Select the nodes for adding lineage diff check
- Check

[Feature] RC-136 Support lineage diff check

---

js/src/components/lineage/LineageView.tsx

UI Improvement
- Auto-resize the lineage view when the window size changes or the detail view is shown/hidden.
RC-151
#167

[Feature] rc-151 auto resize the lineage view when size change

---

js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/querydiff.tsx

Feature
- hint users that the chosen columns are not valid to be the primary key
RC-125
NONE

[Feature] Add warning when the columns are invalid to be a primary key

---

js/app/page.tsx
js/src/lib/hooks/LineageGraphContext.tsx
recce/dbt.py

Feature
- In the demo sites, we want to show the PR information.
RC-171
NONE

[Feature] Add top bar for showing information

---

js/app/page.tsx

Bug
- page height is too high when top bar existence
RC-213
NONE

[Bug] Fix page height when top bar existence

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/custom.md
.github/ISSUE_TEMPLATE/feature_request.yml

Repo Infra
Remove `linear` label from default issue templates
N/A

[Infra] Remove linear label from issue template

---

recce/tasks/valuediff.py

[Bug] Fix value diff not working in postgres 14

---

recce/apis/run_func.py
recce/exceptions.py

Bugfix
- Catch division by zero error when profiling an empty model on the Snowflake platform.
- Throw a meaningful message instead of throwing what DB gives.
#204 

[Bug] DRC-250 Fix profile diff division by zero error on snowflake

---

recce/tasks/top_k.py

Feature
- The base queries will be based on the result and order of the current top-k result

[Feature] DRC-210 Top-K query result will be based on the current result

---

js/src/components/lineage/NodeSelector.tsx
js/src/components/valuediff/ValueDiffForm.tsx

The execute button should be enabled if primary key is inferenced

[Bug] the value diff execute is not enabled if the PK is inferenced

---

js/src/components/check/CheckListLoader.tsx
js/src/components/check/CheckPage.tsx

Bug
- After loading a state file, it should select the first loaded check.
DRC-263
NONE

[Bug] Show the first check of the loaded checklist

---

js/src/components/valuediff/ValueDiffForm.tsx

[Bug] Fix the default pk issue

---

js/app/page.tsx
js/package.json
js/pnpm-lock.yaml
js/src/components/errorboundary/ErrorBoundary.tsx

Add the error boundary to prevent to show blank page of the whole screen.
see https://legacy.reactjs.org/docs/error-boundaries.html

[Feature] Add error boundary

---

recce/dbt.py

[Bug] Fix the schema diff column name is wrong

---

js/src/components/charts/HistogramChart.tsx
js/src/components/histogram/HistogramDiffResultView.tsx

Feature
- Merge two diff histogram charts into one
- Show percent of total in tooltip with both base & current count.

[Feature] DRC-222 Merge 2 histogram charts into a single histogram chart

---

js/src/components/charts/TopKSummaryList.tsx
js/src/components/top-k/TopKDiffResultView.tsx

Feature
Refine the UI of Top-K by merging 2 bar charts into a single bar chart

[Feature] DRC-207 design the UI component to show the diff of top k

---

js/src/components/data-grid/ScreenshotDataGrid.tsx
js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/QueryResultView.tsx
js/src/components/rowcount/RowCountDiffView.tsx
js/src/components/run/RunView.tsx
js/src/components/schema/SchemaView.tsx
js/src/components/valuediff/ValueDiffDetailResultView.tsx
js/src/components/valuediff/ValueDiffResultView.tsx

Feature
- show `no data` when zero row of the query result
DRC-127
<details><summary>screenshot</summary>
- query
- query diff
</details>
NONE

[Feature] Show no data when zero row of the query result

---

js/src/components/charts/HistogramChart.tsx
js/src/components/charts/SquareIcon.tsx
js/src/components/charts/TopKSummaryList.tsx
js/src/components/check/LineageDiffView.tsx
js/src/components/check/SchemaDiffView.tsx
js/src/components/histogram/HistogramDiffForm.tsx
js/src/components/histogram/HistogramDiffResultView.tsx
js/src/components/top-k/TopKDiffResultView.tsx

Refine
- Refine the UI code of Histogram Chart

[Refine] DRC-222 Update UI code of Histogram Chart

---

.github/workflows/bump.yaml

chore
- auto bump dev version and create a PR
NA
NONE

[Chore] Add bump dev version workflow

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckPage.tsx

Bug
- There's unexpected format when copying markdown of the checklist
DRC-148
NONE

[Bug] Fix format of the checklist copying in markdown

---

js/src/components/lineage/GraphNode.tsx

Feature
- The schema diff result would be materialized from `catalog.json` and shown with row count diff.
DRC-277
NONE

[Feature] Show the schema diff in the lineage graph node

---

recce/apis/check_api.py
recce/models/state.py
recce/models/util.py
tests/models/test_state.py

Bug
- In `dbt 1.6`, it depend on `pydantic v1` due to `dbt-semantic-interfaces`
DRC-274
NONE

[Bug] Fix pydantic dependency of dbt 1.6

---

js/src/components/lineage/lineage.ts

Enhancement 
- `base` -> `both` -> `current`

[Feature] DRC-295 sort the edges by `from` property

---

js/src/components/screenshot/ScreenshotBox.tsx

UI Improve
- Only show the scrollbar-y in Top-K chart
DRC-313

[Fix] DRC-313 only show the scrollbar-y in top-k chart

---

js/src/components/lineage/GraphNode.tsx

Bug
Fix schema diff modified check statement
DRC-323
NONE

[Bug] Fix schema modified check statement

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckList.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/NodeFilter.tsx
js/src/components/lineage/NodeSelector.tsx
js/src/components/lineage/NodeTag.tsx
js/src/components/run/RunModal.tsx
js/src/components/run/RunPage.tsx
js/src/components/run/RunView.tsx
js/src/components/run/registry.ts
js/src/components/run/types.ts
js/src/components/valuediff/valuediff.tsx
js/src/lib/hooks/RecceActionContext.tsx

There are many similar logic to get the run type specific definitions, such as
- result view
- form
- icon
- title
In this PR, we centralize the definition in a registry file.

[Chore] Add registry for run types

---

js/src/components/run/RunModal.tsx
js/src/components/valuediff/ValueDiffDetailResultView.tsx
js/src/components/valuediff/ValueDiffForm.tsx
js/src/components/valuediff/ValueDiffResultView.tsx
js/src/lib/api/valuediff.ts
recce/tasks/valuediff.py

Fix #203 
Support to select multiple columns as primary key.

[Feature] Support value diff for models with composite primary key

---

js/src/components/lineage/LineageView.tsx

Steps:
- Prepare target/ and target-base with same manfiest.json
- Run `recce server`
- it would show no nodes. Click "Show all nodes" button
- Even change to all nodes, it still show nothing

[Bug] lineage view shows nothing if there is no modified model

---

.github/ISSUE_TEMPLATE/bug_report.yml

Update the bug_report template.

[Chore] Update bug_report.yml

---

recce/tasks/rowcount.py

- Don't show error if table does not exist
- Don't submit query for non-exist table.

[Bug] Don't query row count if the model does not exist

---

recce/apis/run_func.py
recce/dbt.py
recce/tasks/core.py

Bugfix
- SQL query should still work under review mode
- Still load `base` & `current` manifest even under review mode
- Throw the user-readable error message when the server is running under review mode and without the correct dbt project setting.

[Bug] DRC-344 SQL query should still work under review mode

---

js/src/components/lineage/LineageView.tsx

Fit the view if the nodes changes in the lineage page.

[Enhancement] Fit view after filter change

---

recce/dbt.py
recce/server.py

The runs and checks are not loaded while launching the recce server

[Bug] Should load the runs/checks at the startup

---

js/src/components/histogram/HistogramDiffForm.tsx
js/src/components/top-k/TopKDiffForm.tsx
js/src/components/valuediff/ValueDiffForm.tsx
js/src/lib/api/info.ts
js/src/lib/hooks/useModelColumns.tsx
recce/dbt.py
recce/server.py

Feature
- to optimize the diff task when it lacks of column information
DRC-321
NONE

[Feature] Query the model when the run form lacks column information

---

recce/git.py

Bug
- Getting branch name raises exception when the HEAD is detached.
DRC-366
NONE

[Bug] Handle getting branch information when HEAD is detached

---

.flake8
recce/dbt.py

Chore
- prepare dbt context without doing dbt parse which pollute the current environment
DRC-354
NONE

[Feature] Allow to review without models source code

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckDetail.tsx
js/src/components/check/PresetCheckTemplateView.tsx
js/src/components/run/RunView.tsx
js/src/lib/api/checks.ts
recce/apis/check_api.py
recce/apis/check_func.py
recce/cli.py
recce/config.py
recce/dbt.py
recce/models/types.py
recce/run.py
recce/util/__init__.py
recce/util/singleton.py

Feature
- Dump the template of recce config with an example of preset check
- Execute the preset checks when executing `recce run`
- Mark the check if it's preset check

[Feature] DRC-357 Load and dump empty recce config file with preset checks

---

js/app/page.tsx
js/src/lib/api/info.ts
js/src/lib/hooks/LineageGraphContext.tsx
recce/server.py

Chore
- Add explicit demo site information to the server info API
DRC-355
NONE

[Chore] Add demo instance info to the server info api

---

recce/models/check.py

Bug
- deleting a check is not working
- DRC-373
NONE

[Bug] Cannot delete added check

---

recce/run.py

Bugfix
Schema diff don't need to execute run when running preset check

[Bug] DRC-359 Fix schema diff issue when execute preset check

---

js/src/components/check/CheckDetail.tsx
js/src/components/run/RunView.tsx

Bugfix
- If a check don't have run result, only show the `Run Query` button in the Check Detail page. Otherwise, show `No Data`

[Bug] DRC-374 only show Run Query button in CheckDetail page

---

.github/workflows/build-statics.yaml

Infra
Build static files on release branches
N/A

[Infra] Build static files on release branches

---

.github/workflows/build-statics.yaml
js/src/components/check/CheckDetail.tsx
js/src/components/run/RunView.tsx
recce/run.py

Hotfix
- [Bug] DRC-359 Fix schema diff issue when executing preset check #277
- [Bug] DRC-374 only show Run Query button in CheckDetail page #278
- [Infra] Build static files on release branches #279
N/A

[Hotfix] v0.13.1 Fix recce ci issues

---

.github/workflows/build-statics.yaml

Infra
Fix build statics action issue
N/A

[Infra] Fix build statics action

---

js/app/page.tsx
js/src/components/check/StateExporter.tsx
js/src/components/check/StateImporter.tsx
js/src/components/env/EnvInfo.tsx
js/src/lib/api/info.ts
js/src/lib/hooks/LineageGraphContext.tsx
recce/adapter/dbt_adapter.py
recce/core.py
recce/pull_request.py
recce/run.py
recce/server.py
recce/state.py
tests/test_pull_request.py

Feature
- Add env information to hint users
DRC-327
NONE

[Feature] Enhance clarity regarding the baseline and current environment

---

.github/workflows/eslint.yaml
.github/workflows/tests.yaml
recce/adapter/dbt_adapter.py

1. Launch recce in the review mode
```
recce server --review recce_state.json
```
2. Use the value diff

[Bug] The value diff is not working in the review mode.

---

recce/adapter/dbt_adapter.py
recce/cli.py
recce/server.py

[Bug] reivew mode should be able to be launched when the dbt project or profile is absent.

---

recce/core.py

Expected
1. Should launch successfully,
2. When terminating, create the file and save the result to the file.

[Bug] Cannot launch recce server if the state file does not exist

---

js/src/components/data-grid/ScreenshotDataGrid.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/screenshot/ScreenshotBox.tsx
js/src/lib/hooks/ScreenShot.tsx

Bug
fix compatibility issue of copying screenshot to the clipboard on different browsers. 
- wrong element transformation on the latest firefox 
- security limitation on safari
DRC-385
NONE

[Bug] Fix failed to copy screenshots

---

js/src/components/env/EnvInfo.tsx
js/src/lib/api/info.ts
recce/state.py

Bug
- In review mode, recce server would read state file and do basic type validation.
DRC-387
NONE

[Bug] State file type validation rule

---

recce/adapter/dbt_adapter.py
recce/cli.py
recce/summary.py

Feature
- Use mermaind markdown to describe lineage graph

[Feature] DRC-389 Add new command `recce summary` to generate markdown

---

.github/workflows/tests.yaml

Add python pip cache

---

.flake8
.github/workflows/eslint.yaml
.github/workflows/tests.yaml
js/src/components/lineage/NodeView.tsx
js/src/lib/api/info.ts
js/src/lib/hooks/LineageGraphContext.tsx
recce/adapter/base.py
recce/adapter/dbt_adapter.py
recce/adapter/sqlmesh_adapter.py
recce/apis/run_func.py
recce/cli.py
recce/core.py
recce/run.py
recce/server.py
recce/summary.py
recce/tasks/dataframe.py
recce/tasks/query.py
recce/tasks/rowcount.py

Resolve #273 
This is the first version of SQLMesh integration.
The PR includes
1. Launch recce to compare one env against prod env
2. Show lineage diff
3. Show schema diff
4. Support query diff
5. Support row count diff
Feature

SQLMesh integration

---

recce/adapter/sqlmesh_adapter.py
recce/cli.py

```
recce serer --sqlmesh --sqlmesh-envs prod:dev --sqlmesh local_config
```

[Feature] SQLlMesh integration: add --sqlmesh-config option

---

js/src/components/env/EnvInfo.tsx
js/src/components/query/QueryPage.tsx
js/src/lib/api/info.ts
js/src/lib/hooks/LineageGraphContext.tsx
js/src/lib/hooks/RecceQueryContext.tsx
recce/adapter/sqlmesh_adapter.py
recce/server.py
recce/tasks/dataframe.py
recce/tasks/rowcount.py

[Chore] Polish the SQLMesh Integration

---

integration_tests/sqlmesh/config.py

Fix typo
Fix flake8 failed issue
N/A

[Fix] Update config.py for flake8 issue

---

recce/summary.py
setup.py

Bugfix
- Add message when no lineage graph change
- Add missing python dependency

[Bug] add missing dependency

---

integration_tests/dbt/smoke_test.sh

Fix Smoke Test CI. Unbounded variable

Fix Smoke Test CI. Unbounded variable

---

recce/summary.py

Enhance
- Show the the number of total & impacted checks as a check summary
- Remove type of changes in impacted checks table

[Feature] Remove type of changes in impacted checks table

---

recce/summary.py
recce/tasks/query.py
recce/tasks/valuediff.py

Feature
- The query diff now has two different result formats, so the recce summary needs to support both.
DRC-411
NONE

[Feature] Support to parse query diff with joins result when doing summary

---

recce/tasks/valuediff.py

[Bug] Add import agate

---

js/src/components/query/QueryDiffResultView.tsx
js/src/components/run/RunToolbar.tsx
js/src/components/valuediff/ValueDiffDetailResultView.tsx

Feature
- If there is no change, it shows no change and cannot toggle back when toggle the "Changed only" checkbox
DRC-401

[Feature] Support changed only toggling on run toolbar

---

recce/adapter/sqlmesh_adapter.py
recce/tasks/query.py

Specify the primary key to be diff in the warehouse.

[Feature] SQLMesh: Add query diff with join

---

recce/summary.py

Enhancement
- Rename impacted to Data Mismatch Detected
- Remove descrition field from check table
- Add related models field to check table
- List all the related models
- Query diff checkk will be `N/A` due to we can't detect the related modules without parsing the raw SQL
DRC-418

[Feature] DRC-418 Fix feedback issues

---

recce/adapter/base.py
recce/adapter/sqlmesh_adapter.py

It should not use the dbt data structure.

[Bug] Fix add schema check not working in sqlmesh

---

js/src/components/query/querydiff.tsx
js/src/components/valuediff/valuediff.tsx

[Bug] Should show null in the queryquery diff result

---

js/src/components/query/QueryForm.tsx

Chore
- revise hint message of query diff form
DRC-375
NONE

[Chore] Revise the hint message of query diff form

---

js/src/components/query/querydiff.test.ts
js/src/components/query/querydiff.tsx

[Enhancement] Show '-' if the value is not available

---

js/src/components/query/querydiff.test.ts
js/src/components/query/querydiff.tsx
js/src/components/valuediff/valuediff.tsx

In the query dff in the warehouse and value diff detail, show all columns if there is only added/removed reocrds

[Enhancement] Show all columns if the diff results have only added or removed records

---

integration_tests/dbt/smoke_test.sh

Chore
- Fix dbt smoke test when merging into the main
NONE

[Chore] Fix dbt smoke test when merging into the main

---

recce/cli.py

Fix
Hidden the format option in summary command

[Fix] Hidden summayr format option

---

recce/cli.py
recce/config.py
recce/event/track.py
recce/run.py
recce/summary.py
recce/tasks/core.py

[Fix] DRC-417 Handling the check error when execute recce run

---

recce/event/__init__.py

Chore
- To differentiate dbt users and sqlmesh users
DRC-428
NONE

[Chore] Add adapter type telemetry

---

recce/server.py

[Enhancement] Add gzip compression

---

recce/core.py

[Bug] The cli option target is not used in the review mode

---

recce/__init__.py
recce/event/__init__.py
recce/event/collector.py
recce/event/track.py
recce/git.py

Chore
- to track what environment Recce runs on
- to track how many projects used Recce
drc-477
NONE

[Chore] Track running environment and repository

---

recce/git.py
recce/github.py

Feature
- Fetch PR information base on local git repository setting
DRC-496
NONE

[Feature] Fetch PR information base on branch and remote

---

js/src/lib/api/info.ts
js/src/lib/hooks/LineageGraphContext.tsx
recce/apis/check_func.py
recce/cli.py
recce/core.py
recce/github.py
recce/models/run.py
recce/pull_request.py
recce/run.py
recce/server.py
recce/state.py
recce/util/logger.py
setup.py

Feature
- Abstract the recce_state I/O by RecceStateLoader class
- Add options `--cloud`, `--cloud-token`, and `--state-file-host` for CLI
- Fetch/upload the recce state from cloud storage
- Support access recce state by specific AWS s3 bucket

[Feature] DRC-494 Abstract recce_state I/O by RecceStateLoader class

---

recce/pull_request.py

Bugfix
- Fix type error issue when calling method `recce_pr_information`

[Fix] DRC-502 Fix typeerro issue when calling recce_pr_information

---

recce/state.py

Enhancement
- Compress the recce state by gzip when upload/download to cloud storage

[Feature] DRC-501 Compress when upload/download the recce state to cloud

---

recce/state.py

Bugfix
Fix recce `--cloud` option doesn't compress the state content issue

[Fix] DRC-518 Recce cloud option didn't compress the state content

---

js/src/components/lineage/NodeView.tsx
js/src/components/lineage/styles.tsx
recce/adapter/dbt_adapter/__init__.py

[Feature] Add snapshot node in the lineage graph

---

js/src/components/lineage/NodeView.tsx
js/src/components/lineage/styles.tsx
recce/adapter/dbt_adapter/__init__.py

Add snapshot in the lineage

---

recce/adapter/dbt_adapter/__init__.py
tests/adapter/dbt_adapter/test_dbt_adapter.py

The dbt adapter has a node selector methods

[Feature] Add the select nodes method

---

recce/adapter/base.py
recce/adapter/dbt_adapter/__init__.py
recce/server.py

Add the endpoint `/api/select`
Request
```bash
curl -X POST "http://localhost:8000/api/select" -H "Content-Type: application/json" -d '{"select": "state:modified+", "exclude": "customer_order_pattern"}' | jq .
```
Response
```json
{
"nodes": [
"model.jaffle_shop.customer_segments",
"model.jaffle_shop.customers",
"model.jaffle_shop.customers_view"
]
}
```

[Feature] Add the select api endpoint

---

js/app/layout.tsx

[Chore] Update the recce server meta.description

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckPage.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/styles.css
js/src/components/split/Split.tsx
js/src/components/split/styles.css

Support to resize the pane in the three main pages.
Enhancement

[Enhacenmet] use splitter in the UI

---

js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckPage.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/styles.css
js/src/components/split/Split.tsx
js/src/components/split/styles.css

[Feature] Add splitter

---

js/src/components/schema/schema.tsx

[Enhancement] Set the size of the index column of the schema view

---

recce/cli.py
recce/state.py
setup.py
tests/test_cli.py

Feature
- Change to use zip instead of gzip
- Add `--password` option when enable cloud mode
**TODO**

[Feature] Implement password protect cloud state file

---

js/src/components/rowcount/RowCountDiffResultView.tsx

Feature
Hint user there's no node matched instead of empty result.
DRC-508
NONE

[Bug] Show no match when row count diff selection no match

---

integration_tests/dbt/smoke_test.sh
recce/adapter/dbt_adapter/__init__.py
recce/config.py
recce/run.py

Change the `recce.yml` template. Add the default preset checks
1. Row count diff for all modified table models
1. Schema diff for all nodes

[Feature] Provide the default preset checks

---

recce/cli.py

[Chore] Update the CLI command description

---

js/src/components/check/CheckDetail.tsx

Chore
change checks status wording
DRC-529
NONE

[Chore] Change check status wording

---

recce/models/check.py
recce/state.py

Feature
- Add check's status in metadata when uploading to cloud
- total checks
- approved checks
- Implement get artifact metadata method for both recce cloud and s3 bucket

[Feature] DRC-533 Add check's status in metadata when upload to cloud

---

js/src/components/lineage/LineageView.tsx
js/src/components/lineage/NodeFilter.tsx
js/src/components/lineage/NodeSelector.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/lineage/graph.ts
js/src/components/lineage/lineage.ts
js/src/lib/api/checks.ts
js/src/lib/api/lineagecheck.ts
js/src/lib/api/schemacheck.ts
js/src/lib/api/select.ts
recce/apis/check_func.py
recce/server.py
recce/tasks/rowcount.py

1. Support to filter nodes by node selector select and exclude
1. Support to add the lineage diff check by current setting
1. Support to run the row count diff by selector
1. Support to add the schema diff check by selector

[Feature] Support node selector in the lineage diff view

---

recce/adapter/dbt_adapter/__init__.py
recce/run.py
recce/summary.py
recce/tasks/core.py
recce/tasks/rowcount.py
recce/tasks/schema.py

Feature
Row count diff and schema diff support the selector now.
In recce summary, we want to show related models based on the selection result.
DRC-523
NONE

[Feature] Summary supports row count and schema diff with node selector

---

recce/adapter/dbt_adapter/__init__.py
tests/adapter/dbt_adapter/dbt_test_helper.py
tests/adapter/dbt_adapter/test_selector.py

Support to select the removed node by node selection.

[Enhancement] Support to select removed node by graph operator

---

recce/summary.py

Chore
- Refine summary content
NONE

[Chore] Refine summary mismatched nodes content

---

recce/cli.py
recce/state.py
recce/util/recce_cloud.py

Feature
- Cloud mode with `--state-file-host` also support GitHub App check runs
- Refine state.py, extract RecceCloud-related methods to another file

[Feature] DRC-531 --state-file-host also support GitHub App

---

.github/workflows/build-statics.yaml
.github/workflows/nightly.yaml
.github/workflows/release.yaml
.github/workflows/tests-js.yaml

Fix pnpm ci issue

---

js/src/components/lineage/NodeSelector.tsx

Bug
Fix adding schema diff check to multiple nodes
DRC-551
NONE

[Bug] Fix adding multiple schema checks to nodes

---

recce/cli.py

Enhance UX
- If the giving output path is a directory, append the default state file at the end.
- Ex: recce run -o .recce/ -> Save the state file at `.recce/recce_state.json`
- If the sub-dirs of the output path do not exist, execute mkdir to create them.
- Ex: recce run -o tmp1/tmp2/tmp3/tmp4/recce_state.json -> Create the folder if it doesn't exist. 

[Enhance] Handle the edge case of output file path is dir or not exist

---

js/src/components/query/QueryDiffResultView.tsx

Bug
- To use the correct query diff result view component (the variable `diff` can be undefined)
DRC-563
NONE

[Bug] Use correct query diff result view component

---

recce/run.py

Feature
- Refine the recce run behavior with given state file
DRC-550
NONE

[Feature] Adjust recce run behavior when given state file

---

recce/util/recce_cloud.py

Chore
- Set the default recce cloud endpoint to the production
DRC-564
NONE

[Chore] Set the default recce cloud endpoint to production env

---

recce/cli.py
recce/state.py
recce/util/recce_cloud.py

Feature
- Add addition GitHub App installation check on Recce Cloud
DRC-558
NONE

[Feature] Check if GitHub APP authorize the repository

---

recce/github.py
recce/state.py

Checks the following case
1. Not in git repo
2. Not a github repo 
3. A private repo but the token has no `repo` scope
4. No PR found
5. GitHub App is not installed.

[Enhancement] Fix the error message for cloud mode

---

README.md

fix typo, move Who's using Recce? section

---

recce/tasks/schema.py

Fix #401 
The recce summary would raise exception if there are nodes removed
Bug fix

[Bug] The recce summary would raise exception if there are nodes removed

---

js/src/components/check/SchemaDiffView.tsx

Shows the added and removed nodes in the schema diff check.
Before
After

[Enhancement] Schema diff check shows the added and removed nodes

---

recce/state.py

Bugfix
Remove the logic of appending tag when uploading data to S3 presigned url

[Fix] DRC-618 Remove s3 tag when uploading data to presigned URL

---

recce/cli.py
recce/state.py
recce/util/io.py
recce/util/recce_cloud.py

Feature
- add cloud subcommand to manipulate cloud state file
DRC-601
NONE

[Feature] Add cloud subcommand

---

recce/cli.py
recce/run.py
recce/state.py
recce/summary.py
recce/tasks/core.py

Feature
- new usage of recce run:
we can generate recce summary with recce run in one pass
`recce run --summary <file.md>`
- recce summary format
add manifest metadata information
add recce cloud pr page link if in cloud mode
DRC-620
NONE

[Feature] recce summary should be up-to-date

---

recce/core.py

Recce server should not be able to launch if no state available in the review mode

---

recce/event/__init__.py
recce/event/collector.py
recce/event/track.py
recce/github.py

Feature
- Collect 2 new events by amplitude 
- `codespace_instance_created` based on the `created_at` field
- `codespace_instance_available` based on the latest log file under `/tmp/codespaces_logs/`
- The `codespace_instance_created` and `codespace_instance_created` will be stored into `~/.recce/profile.yml`. We won't resend the created & available events twice.

[Feature] DRC-625 Telemetry for codespaces related actions

---

recce/event/__init__.py
recce/event/track.py
recce/github.py

Feature
- Send telemetry before server command started
- Codespace information will be also send before command started

[Feature] DRC-625 Send telemetry event before server started

---

js/app/page.tsx

- Feature
- provide information of how many pending checks are there
DRC-616
NONE

[Feature] Add badges for pending checks

---

js/src/components/lineage/ActionTag.tsx
js/src/components/lineage/NodeFilter.tsx
js/src/components/lineage/NodeTag.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/schema/SqlDiffView.tsx

Make the node actions together

---

recce/github.py
recce/pull_request.py
recce/state.py

Feature - refine output message
Refine output message
DRC-570
NONE

[Feature] Refine PR information warning message

---

js/src/components/histogram/HistogramDiffForm.tsx

Feature change
The histogram diff only accepts numeric columns.
We should fix error message when there's no numeric message.
DRC-692
NONE

[Bug] Fix histogram diff wrong message

---

recce/run.py

Feature change
check results of `recce run` should not return failed exit code
DRC-648
NONE

[Feature] Modified recce run return code

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckList.tsx
js/src/components/lineage/NodeFilter.tsx

1. The pending/approve toolip in the approve/pending button
2. The lineage view action button popover
3. The check reorder offset issue

[Bug] Fix the layout problem in the check and lineage UI

---

recce/adapter/dbt_adapter/__init__.py

Bugfix
- Support `metric` and `semantic_model` when Recce try to parse the dbt manifest file

[Fix] DRC-717 Recce should support `metric` and `semantic_model` nodes

---

js/src/components/lineage/NodeSelector.tsx
js/src/components/query/QueryResultView.tsx
js/src/components/run/RunToolbar.tsx

[Feature] Change add to checklist button in query UI

---

js/app/page.tsx
js/src/components/onboarding-guide/OnboardingGuide.tsx

Feature
- Show the onboarding guide when the user accesses the Recce Server the first time
- Save the visit information in the user's browser local store

[Feature] show onboarding gudie when first time open

---

js/src/components/onboarding-guide/OnboardingGuide.tsx

Bugfix
- Fix onboarding modal layout issue

[Fix] DRC-723 fix onboarding modal layout issue

---

js/app/page.tsx
js/src/components/lineage/LineagePage.tsx
js/src/components/query/QueryPage.tsx
js/src/components/run/RunResultPane.tsx
js/src/components/schema/SchemaView.tsx
js/src/lib/hooks/RecceActionContext.tsx

Update the query page. Make the run result pane same as the one in the lineage page.
Feature

[Feature] Add run result pane in the query page

---

js/app/page.tsx

Feature
- In cloud mode, PR information is ready. Hence, we would like to make it convenient to visit the PR.
DRC-695
NONE

[Feature] Add pr link info beside cloud mode badge

---

js/app/page.tsx

Feature
Rename `Checks` tab into `Checklist`.
DRC-682
NONE

[Feature] Rename checks tab to checklist

---

recce/yaml/__init__.py
setup.py

Bump up ruamel.yaml

---

recce/summary.py

Bug
To draw the mermaid diagram level-by-level to make it doesn't exceed the mermaid `maxTextSize`
DRC-542
NONE

[Bug] Make mermaid diagram don't exceed the max text size

---

recce/apis/check_api.py
recce/apis/run_api.py

Chore
Remove sensitive info from telemetry
PLA-6

Remove params and view_options from api events

---

js/app/page.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/NodeFilter.tsx
js/src/components/query/QueryPage.tsx
js/src/components/run/RunList.tsx
js/src/components/run/RunResultPane.tsx
js/src/components/run/RunView.tsx
js/src/components/valuediff/ValueDiffResultView.tsx
js/src/lib/api/cacheKeys.ts
js/src/lib/api/runs.ts
js/src/lib/api/types.ts
js/src/lib/hooks/RecceActionContext.tsx
recce/apis/check_func.py
recce/apis/run_api.py
recce/apis/run_func.py
recce/models/types.py

Add additional run history in the lineage and query pages. This feature allows user to navigate the historical runs and do the back&forth exploration.
Feature

[DRC 700] show the run history in the run result pane

---

js/package.json
js/pnpm-lock.yaml
js/src/components/run/RunList.tsx
js/src/lib/api/types.ts

Make the scrollbar of the history overlayed

---

js/src/components/check/StateImporter.tsx
js/src/components/check/StateSynchronizer.tsx
js/src/components/run/RunList.tsx
js/src/components/run/RunResultPane.tsx
js/src/lib/api/types.ts
js/src/lib/hooks/useRun.tsx
recce/apis/run_func.py
recce/models/types.py

[Enhancement] in history list, update the running status if a run is still running

---

js/src/components/check/CheckDetail.tsx

It calls the cancel while rerun and leave a check detail page.
Bug

[Bug] Dont cancel a run while leaving the check detail page

---

js/src/components/lineage/NodeSelector.tsx

1.  Select multi node
2. Run row count idff
3. The result pane should show up.

[Bug] Should update the check result panel when running multi-model row count diff

---

js/src/components/query/QueryForm.tsx

[Enhancement] Update the message for primary keys

---

recce/event/__init__.py
recce/event/track.py

Chore
Add hashed repo name and branch title to telemetry event for better product analysis
DRC-798

Add hashed repo and branch info to telemetry

---

js/src/components/check/CheckDetail.tsx
js/src/components/data-grid/ScreenshotDataGrid.tsx
js/src/components/histogram/HistogramDiffResultView.tsx
js/src/components/profile/ProfileDiffResultView.tsx
js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/QueryResultView.tsx
js/src/components/rowcount/RowCountDiffResultView.tsx
js/src/components/run/RunList.tsx
js/src/components/run/RunResultPane.tsx
js/src/components/run/RunStatusAndDate.tsx
js/src/components/run/RunView.tsx
js/src/components/run/registry.ts
js/src/components/screenshot/ScreenshotBox.tsx
js/src/components/top-k/TopKDiffResultView.tsx
js/src/components/valuediff/ValueDiffDetailResultView.tsx
js/src/components/valuediff/ValueDiffResultView.tsx
js/src/lib/hooks/ScreenShot.tsx

This is a UI enhancement PR. We moved the "Copy to clipboard" button to the toolbar instead of the button on the bottom-right corner.
UI Enhancement

[Enhancemnt] Move the copy to screenshot button to the toolbar

---

recce/adapter/dbt_adapter/__init__.py
recce/cli.py
tests/adapter/dbt_adapter/dbt_test_helper.py

Feature
- To allow specifying custom `target` path and `target-base` path
DRC-721
NONE

[Feature] Allow custom target path and target base path for recce server

---

README.md

Update ReadMe.
Add cal.com links per sponsorship criteria.
N/A
Only readme text updated.

Added cal.com banners. Fixed incomplete sentence

---

recce/state.py

Bugfix
- Add Tagging information when calling the upload resigned URL

[Bug] DRC-832 Fix recce checks status doen't shown on Cloud page

---

js/src/components/rowcount/RowCountDiffResultView.tsx

[Bug] Fix row count diff should show 0 if no rows

---

recce/adapter/dbt_adapter/__init__.py

bug
- add the missing parsing function of the `exposures` node toward dbt manifest
DRC-843
NONE

[Bug] Cannot find exposures node name in dbt manifest

---

js/src/components/valuediff/ValueDiffResultView.tsx

[Bug] Unable to see full value diff actions

---

js/src/components/query/QueryPage.tsx

UI Fix
The Run Diff button should align with primary key input field

[Fix] Fix Run Diff button height

---

js/app/page.tsx

[Enhancement] Change the demo site PR indicator.

---

README.md

Read me update
Internally requested
Engagement on the repo.
N/A
yes, Readme page

Updated the readme with developer-focused intro

---

js/app/page.tsx
js/src/components/charts/HistogramChart.tsx
js/src/components/histogram/HistogramDiffResultView.tsx
js/src/components/top-k/TopKDiffResultView.tsx

Feature
-  to view histogram chart comfortably
DRC-779
NONE

[Feature] View histogram comfortably

---

js/app/page.tsx
js/package.json
js/pnpm-lock.yaml
js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckList.tsx
js/src/components/check/CheckPage.tsx
js/src/lib/hooks/useCheckToast.tsx
js/theme/components/Checkbox.ts
js/theme/components/Tooltip.ts
js/tsconfig.json

Feature
- Make the checkbox clickable in the `Check List View`
- Show the warring model if users check a check from the list view directly.
- The warring model can be bypassed if you confirm it.
- Show a toast when a Check is checked.

[Feature] DRC-879 Refine the UI of checklist page

---

js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewTopBar.tsx

[Feature] Support to run lineage actions in single-selected mode

---

recce/apis/check_func.py
recce/cli.py
recce/server.py
recce/state.py

Bug
- Upload state file right after adding a check when launching recce with `recce server --cloud` 
DRC-840
NONE

[Bug] Sync checks as they are added

---

js/src/components/check/SchemaDiffView.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/useMultiNodesAction.ts
js/src/lib/api/schemacheck.ts
recce/apis/check_func.py
recce/tasks/schema.py

**Before**
It would create n checks for each node
**After**
Create single check with 4 nodes.

[Feature] Support schema diff check with multiple selected nodes

---

js/app/page.tsx

Bugfix
- Disable the scroll bar in the main page of Recce

[Fix] DRC-907 Disable the scroll bar in Recce page

---

js/app/page.tsx
js/src/components/check/StateImporter.tsx
js/src/lib/api/state.ts
recce/core.py
recce/server.py

Feature
- Allow to import checks in recce cloud and review mode
DRC-912
- Import in cloud and review mode

[Feature] Import checklist to cloud mode

---

js/src/components/lineage/ActionTag.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/useMultiNodesAction.ts
js/src/components/lineage/useValueDiffAlertDialog.tsx

1. Use view_mode, packages, select, exclude to select nodes
2. Click Actions > Value Diff
3. It will run value diff just like multi select mode.

[Feature] Support value diff to run all visible nodes in the selector.

---

js/src/components/lineage/LineageView.tsx
js/src/components/lineage/useMultiNodesAction.ts

Just the bug fix of new multi-nodes implementation.

[Bug] Fix multi-nodes bugs

---

js/.env.development
js/app/page.tsx
js/src/components/lineage/LineageView.tsx
js/src/lib/api/track.ts

This is used for do the telemetry for multi nodes events.
Event name: [Web] multi_nodes_action
Props:
type: 'value_diff' | 'row_count_diff' | 'schema_diff' | 'lineage_diff'
selected: 'multi' | 'single' | 'none'

[Chore] Add multi nodes action telemetry

---

.github/workflows/build-statics.yaml

Infra
- Setup main branch after merge pipeline with auto-commit personal token

[Infra] Setup autocommit with personal token

---

recce/summary.py

Bug
We should find the latest run for the check
DRC-931
NONE

[Bug] Adjust finding run logic in recce summary

---

.github/workflows/build-statics.yaml

Infra
Manually trigger frontend static files build action

[Infra] Manually trigger front-end static files build

---

.github/workflows/build-statics.yaml

Infra
Set token when checkout code with building frontend static file

[Infra] Set token when checkout code

---

.github/workflows/build-statics.yaml

Infra
Fix typo in `.github/workflows/build-statics.yaml`

[Infra] Fix typo

---

js/src/components/lineage/ActionTag.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/styles.tsx

Normal mode
Multi-selected mode
Enhancement
Improve the multi-node UI/UX. 

[Enhancement] Update the lineage node outlook

---

recce/tasks/rowcount.py

Support to update current progress for row count diff

[Enhancement] Update the row count diff progress

---

js/src/components/check/CheckDetail.tsx
js/src/components/run/RunResultPane.tsx
js/src/lib/hooks/ScreenShot.tsx

Disable copy to clipboard button if the tabs is not in the result tab

---

.github/workflows/bump.yaml

Chore
- Due to protected branch policy, we need additional PAT to  enable auto-commit
NA
NONE

[Chore] Fix auto commit for protected branch

---

js/src/lib/hooks/LineageGraphContext.tsx

If the server connection is lost, prompt the user to prevent further operations.

[Feature] Prompt the user if connection is lost

---

js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/query/QueryPage.tsx
js/src/components/run/RunList.tsx
js/src/lib/api/track.ts

Add telemetry event `[Web] History Action`
with the name 
```
interface HistoryActionProps {
name: "show" | "hide" | "click_run" | "add_to_checklist" | "go_to_check";
}
```

Add history telemetry actions

---

recce/apis/check_func.py
recce/run.py

Feature
- For `SCHEMA_DIFF` and `ROW_COUNT_DIFF` we will mark as approved if we know the result don't have any changes

[Feature] DRC-935 Auto-approved the preset check if we know the result

---

recce/cli.py

Feature
- Add the debug option flag for the command `download-base-artifacts`

[Feature] DRC-916 Add debug option on command download-base-artifacts

---

recce/cli.py
recce/config.py
recce/event/track.py
recce/exceptions.py
recce/models/types.py
recce/tasks/core.py
recce/tasks/histogram.py
recce/tasks/lineage.py
recce/tasks/profile.py
recce/tasks/query.py
recce/tasks/rowcount.py
recce/tasks/schema.py
recce/tasks/top_k.py
recce/tasks/valuediff.py
tests/adapter/dbt_adapter/dbt_test_helper.py
tests/tasks/test_histogram.py
tests/tasks/test_lineage.py
tests/tasks/test_preset_checks.py
tests/tasks/test_profile.py
tests/tasks/test_query.py
tests/tasks/test_row_count.py
tests/tasks/test_schema.py
tests/tasks/test_top_k.py
tests/tasks/test_valuediff.py

1. Prompt error message if preset check format is wrong
2. Add check validator for each check types.

[Enhacnement] add check validator for each check and add unit tests

---

recce/run.py

Bug fix
- When adding or removing the models, one of the `base` and `curr` variables could be None. Should define the initial value of that variable.

[Fix] DRC-935 Handle the edge case when add/remove models

---

js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewContext.tsx

[Bug] Dont show the checkbox in lineage diff check

---

recce/state.py

Fix failure for `recce server --cloud --review`

[Bug] Fix the pr_info issue for recce server --cloud

---

.github/workflows/integration-tests.yaml
recce/adapter/dbt_adapter/__init__.py

Infra
- Once the dbt 1.9 is released. The original smoke will always test the latest verions of dbt-core.
- Add smoke test for dbt-core 1.8 with python 3.11
- Add a new flag defined in dbt 1.9 `state_modified_compare_more_unrendered_values` to pass the test

[Infra] Setup smoke test for dbt 1.7, 1.8 and 1.9

---

Makefile
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/query/QueryForm.tsx
js/src/components/query/QueryPage.tsx
js/src/constants/tooltipMessage.ts
js/src/lib/api/info.ts
js/src/lib/hooks/LineageGraphContext.tsx
js/src/utils/DropdownValuesInput.tsx
recce/adapter/base.py
recce/adapter/dbt_adapter/__init__.py
recce/adapter/sqlmesh_adapter.py
recce/apis/run_func.py
recce/core.py
recce/server.py
recce/tasks/__init__.py
tests/adapter/dbt_adapter/test_dbt_adapter.py

Feature
- Provide the support tasks information in /api/info
- Disable Value Diff and Porfile Diff buttons when the dbt packages are not installed

[Feature] DRC-937 Disable value and profile diff when no packages found

---

js/package.json
js/pnpm-lock.yaml

Security Patch
Bump axio from 1.6.0 to 1.7.9 in /js

[Patch] Bump axio from 1.6.0 to 1.7.9 in /js

---

js/package.json
js/pnpm-lock.yaml

Security Patch
Patch next to version `^14.2.10`

[Patch] Bump next from 14.1.1 to 14.2.10 in /js

---

js/src/components/check/CheckBreadcrumb.tsx
js/src/components/check/CheckDetail.tsx

1. Change to use the empty circle 
2. Fix the too long title layout issue
3. Move the copy markdown to dropdown menu  to save the horizontal space.

[Enhanement] Update the icon for "mark as approved"

---

recce/core.py
recce/server.py

Event name: `api_event`
Payload Example
```json
{
"endpoint_name": "saveas",
"state_loader_mode": "file"
}
```

[Chore] Add rename and saveas telemetry event

---

js/src/components/app/Filename.tsx
js/src/lib/api/checks.ts

Prompt the alert dialog if closing the recce tag in the stateless mode.

[Feature] Add close prompt if it is in stateless mode

---

recce/adapter/dbt_adapter/__init__.py
recce/tasks/query.py

Feature
- It's our new experiment feature, "preview change". It supports running query diff on the current environment.
DRC-970
NONE

[Feature] Support diff query running on current environment

---

js/src/components/lineage/LineagePage.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/lineage/PreviewChangeView.tsx
js/src/components/query/QueryForm.tsx
js/src/components/query/QueryPage.tsx
js/src/components/run/RunResultPane.tsx
js/src/components/run/registry.ts
js/src/components/schema/SqlDiffView.tsx
js/src/lib/api/adhocQuery.ts
js/src/lib/hooks/RecceActionContext.tsx
js/src/utils/DropdownValuesInput.tsx

Feature
- Implement the preview change experiment page
- If no changed node is detected, show all nodes by default.

[Feature] DRC-971 Implement preview change experiment page

---

js/src/components/lineage/PreviewChangeView.tsx

Bugfix
- Reset the SQL code when the Preview Change 

[Fix] DRC-978 Reset the current code when Modal is opened

---

js/src/components/charts/HistogramChart.tsx

UI change
- Change the order of the histogram bar chart.

[Fix] DRC-977 Change the order of historgram dataset

---

setup.py

Chore
- Remove Python 3.8 support
- Change minimum required Python 3.9
DRC-994
#557 

Remove Python 3.8 support

---

js/src/components/onboarding-guide/OnboardingGuide.tsx
js/src/lib/api/cacheKeys.ts
js/src/lib/api/flag.ts
js/src/lib/hooks/useRecceServerFlag.tsx
recce/cli.py
tests/test_cli.py

Feature
- When detect recce server is launched in single env mode, hint users there's a docs for preparing environment.
DRC-982
NONE

[Feature] Add guide for launching server with single target

---

js/app/page.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/NodeView.tsx

Feature
- Hiden the diff action buttons and Query&Check tabs when server is launched with single environment mode

[Feature] DRC-1001 Hiden diff actions when signel env mode

---

js/src/components/lineage/PreviewChangeView.tsx
js/src/components/onboarding-guide/OnboardingGuide.tsx
js/src/lib/api/flag.ts
js/src/lib/hooks/LineageGraphContext.tsx
recce/adapter/base.py
recce/adapter/dbt_adapter/__init__.py
recce/cli.py
recce/core.py
recce/server.py
tests/test_cli.py

Feature
- To hint relaunch recce when base env was added
DRC-984
NONE

[Feature] Hint users to relaunch recce when base was added

---

js/src/components/lineage/PreviewChangeView.tsx

Feature
- Enhance preview change panel clarity
DRC-1008
NONE

[Feature] Enhance clarity of preview change panel

---

recce/__init__.py

Chore
- Remove `isatty` from the `is_ci` function.
- Add common CI environments to identify
DRC-1016

[Chore] Improve is_ci function

---

js/src/components/query/QueryForm.tsx
js/src/utils/DropdownValuesInput.tsx

Chore
The primary key selection box was confusing.
Improve the wording and add a icon to make it clear.
DRC-961

[Chore] Improve primary key selection in query page

---

js/src/components/histogram/HistogramDiffResultView.tsx

Bugfix
The base and current env in histogram diff result was reversed.
DRC-999

[Bugfix] Fix data order of histogram diff result

---

recce/adapter/dbt_adapter/__init__.py

Bugfix
- We should reload both the base and current artifacts.
- Currently, we only update the current artifact. The base artifact will not be changed.

[Fix] DRC-1031 Under single env mode, detect manifest changed issue

---

js/src/lib/hooks/LineageGraphContext.tsx

Feature
- Prevent show duplicate artifacts change notification
DRC-1032
NONE

[Feature] Prevent duplicate artifacts change notification

---

js/src/components/check/CheckBreadcrumb.tsx
js/src/components/check/CheckDetail.tsx

Chore
1. Remove "Checklist > " from title
2. Move the "Preset" label to the end of the title
3. Add a guiding message for preset check with no result
4. Disable the approval button when no result
5. Move the "Rerun" icon to the run result. 
DRC-1023
Regarding point 3, should we have the same behavior of approving from the checkbox in the list?

[Chore] Improvement for checklist

---

recce/config.py

Feature
- Load empty recce.yml config if it's empty

[Feature] DRC-1046 Load empty recce.yml if it's empty

---

js/src/components/app/EnvInfo.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/lineage/PreviewChangeView.tsx
js/src/components/lineage/SandboxView.tsx
js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/querydiff.tsx
js/src/components/run/registry.ts
js/src/components/valuediff/valuediff.tsx
js/src/lib/api/info.ts

Feature
- Rename Preview Change to Sandbox
- Add Schemas and latest update time info in Sandbox page

[Feature] DRC-1034 Rename Preview Change to Sandbox

---

js/src/components/lineage/BreakingChangeSwitch.tsx
js/src/components/lineage/LineageView.tsx

Bug fix
1. The default view mode should be `changed models`
2. It doesn't highlight nodes while changing the view mode.

[Bug] Fix the wrong default view mode and wrong behavior of selecting view mode.

---

recce/adapter/dbt_adapter/__init__.py

Feature
- Load envvar when generate SQL

[Feature] DRC-1053 Support env_var when using Query Diff and Sandbox

---

recce/adapter/dbt_adapter/__init__.py

Chore
Dont show the import agate message. Just tell the user to install dbt.

[Chore] Print pip install message if dbt package not found

---

recce/adapter/dbt_adapter/__init__.py
recce/util/breaking.py
tests/util/test_breaking.py

Enhancement
1. Handle UDTF
2. Pass dialect to the sqlglot

[Enhancement] Enhance the breaking change analysis 

---

js/src/utils/DropdownValuesInput.tsx

Fix #594
Bug fix
The hand craft dropdown menu would show items. It would impact the performance of frontend.
#594

Fix: Primary key dropdown selector takes too long to populate

---

recce/adapter/dbt_adapter/__init__.py

Bug
- use `os.path` to parse path string for cross-platform compatibility
DRC-1061
NONE

[Bug] Fix parsing target type on windows

---

README.md

Add pr44 demo sites: demo for breaking change analysis

---

recce/cli.py
tests/test_cli.py

Bug fix
- Single environment mode should not work when the review mode is enabled

[Fix] DRC-1072 Single env mode should not effect when review enabled

---

js/src/components/lineage/LineageView.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/lineage/lineage.test.ts
js/src/components/lineage/lineage.ts
js/src/components/onboarding-guide/OnboardingGuide.tsx
js/src/components/schema/SchemaView.tsx
js/src/components/schema/schema.tsx

Feature
- To have a better navigation when launching with the single enviroment
DRC-1064
NONE

[Feature] Update lineage graph UI in single env

---

recce/util/breaking.py

Enhancement
Some sql cannot pass the optimize function because no source schema provided. In this case, we should bypass the optimizer.

[Enhancement] Bypass the sql optimizer in the breaking change analysis

---

js/src/components/lineage/LineageView.tsx

Feature
Center the lineage graph with the nodes bounds on react flow initiated.
DRC-1064
NONE

[Feature] Center nodes of lineagegraph on react flow init

---

js/src/components/lineage/SingleEnvironmentQueryView.tsx

Bugfix
Reset the SQL query when change the select node

[Bugfix] DRC-1066 Reset SQL query when change the selected node

---

js/app/page.tsx
js/src/components/lineage/ActionTag.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/NodeTag.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/rowcount/RowCountDiffResultView.tsx
js/src/components/run/registry.ts
js/src/components/summary/SchemaSummary.tsx
js/src/lib/api/models.ts
js/src/lib/api/rowcount.ts
js/src/lib/api/types.ts
js/src/lib/hooks/useRun.tsx
recce/adapter/dbt_adapter/__init__.py
recce/apis/run_func.py
recce/models/types.py
recce/tasks/__init__.py
recce/tasks/rowcount.py

Feature
Add row count query to single env mode
NONE

[Feature] Add single env row count query

---

recce/event/__init__.py
recce/server.py

Feature
- Record launching server mode (single env /two env)
NONE

[Feature] Add env information to load state event

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/PresetCheckTemplateView.tsx

Feature
Click the `copy` will copy to template to clipboard

[Feature] DRC-1074 Let `copy` clickalbe and copy template to clipboard

---

js/src/components/lineage/ActionTag.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewContext.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/lineage.ts
js/src/components/lineage/useMultiNodesAction.ts
js/src/lib/api/track.ts

- Fix lineage graph mouse leave deselected issue
- Show row count action when multi-select mode in single environment 

[Fix] DRC-1080 Fix lineage graph mouse leave deselected issue

---

recce/config.py
tests/test_config.py

Bug
`recce.yml` could have 'checks' key without giving values.
In this way, `config.get('checks')` covers no 'checks' key and 'checks' key without values.
DRC-1084
NONE

[Bug] Fix config file with key but without value

---

recce/run.py

Bugfix
- The lineage diff preset check should be supported by recce run 

[Fix] DRC-1090 Preset lineage check should be supported by Run command

---

js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/NodeView.tsx

Feature
- Add `Chevron Down` icon for all the menu buttons. (ex. Mode, Package, Explore Change)
- Resize and change the wording of `Explore Changes` to `Explore` in NodeView
- Resize the button of `Query` when single environment mode 

[UI] DRC-1004 add ChevronDownIcon for all the menu buttons

---

recce/adapter/dbt_adapter/__init__.py
recce/util/cll.py
tests/test_dbt.py
tests/util/test_cll.py

Feature
- refine transformation type for
- parse error
- python model
- source, seed
- no catalog
DRC-1087
NONE

[Feature] Refine transformation type for cll

---

recce/adapter/dbt_adapter/__init__.py
recce/util/cll.py
tests/util/test_cll.py

Feature
- Support the union, intersect, union all
- Fix transformation type for cte with transform
- Map the physical table name to the node unique id
- Handle CLL parse error.
- Exclude base in CLL
NONE

[Feature] Refine the column level lineage logic

---

recce/apis/run_func.py
recce/tasks/valuediff.py

Bugfix
- Catch the exception thrown by SQL query during submit_run
#617

[Fix] DRC-1093 Catch the exception during SQL run

---

js/src/components/lineage/ColumnLevelLineageControl.tsx
js/src/components/lineage/GraphColumnNode.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewContext.tsx
js/src/components/lineage/lineage.ts
js/src/components/schema/ColumnNameCell.tsx
js/src/components/schema/SchemaView.tsx
js/src/components/schema/schema.tsx
js/src/lib/api/info.ts
js/src/lib/api/lineagecheck.ts
recce/adapter/dbt_adapter/__init__.py
recce/util/cll.py
tests/tasks/test_schema.py
tests/test_dbt.py

Support Column Level Lineage (CLL)
Steps
1. Select a model and open side node view.
2. Click the eye icon of a column
3. Enter the CLL mode and you can see the CLL for a column

[CLL] implement the cll frontend

---

js/src/components/lineage/BreakingChangeSwitch.tsx
js/src/components/lineage/ColumnLevelLineageLegend.tsx
js/src/components/lineage/GraphColumnNode.tsx
js/src/components/lineage/LineageView.tsx

[Feature] Refine the CLL UI 

---

js/.editorconfig
js/tsconfig.json

Chore
Updates `tsconfig` to point to `ESNext` as the target - this aligns the current `lib` setting to the same as the target. If `ESNext` is too ambitious, the target can be set to `ES2024` or similar
N/A
- Set target to `ESNext`
- Ensure relative base will resolve to the root `js` directory (add `baseURL`)
- Update .editorconfig - previous `y{a}ml` globbing was causing some issues in WebStorm IDE
**NOTE**: Once this PR is reviewed and accepted, it will be followed-up by another PR that includes the lint updates. I am holding onto that commit here: https://github.com/gcko/recce/commit/824a3b77ae0c5573560e0f0e82eb98b32ff9f27f
**Does …

chore: Update `tsconfig.json`

---

recce/adapter/dbt_adapter/__init__.py
recce/util/cll.py
tests/util/test_cll.py

Feature
- Check CLL stability and availability
NONE

[Feature] CLL stability and availability in snowflake

---

.github/workflows/tests-js.yaml

Infra
- Remove `--max-warrings=0` option, we will allow lint warrings

[Infra] Fix test-js github action workflow

---

.github/workflows/tests-python.yaml
js/src/components/schema/ColumnNameCell.tsx
js/src/lib/api/track.ts
recce/adapter/dbt_adapter/__init__.py
recce/event/__init__.py
recce/util/cll.py

Feature
Track view event and lineage parsing performance
NONE

[Feature] Column level lineage telemetry

---

js/src/components/schema/ColumnNameCell.tsx

[Bug] Fix the menu click three times to open issue

---

js/src/components/lineage/NodeView.tsx
js/src/components/profile/ProfileDiffForm.tsx
js/src/components/run/RunModal.tsx
js/src/components/run/registry.ts
js/src/components/schema/ColumnNameCell.tsx
js/src/lib/api/profile.ts
js/src/lib/hooks/RecceActionContext.tsx
recce/tasks/profile.py
tests/tasks/test_profile.py

Feature
- Profile Diff support column selector
- In the Column Cell dropdown menu, add `Profile Diff` task with selected column only

[Feature] DRC-960 Profile diff support column selector

---

js/src/components/lineage/LineageView.tsx
js/src/components/lineage/lineage.ts
js/src/components/schema/ColumnNameCell.tsx
js/src/components/schema/SchemaView.tsx
js/src/components/schema/schema.tsx
recce/adapter/dbt_adapter/__init__.py

[Enhancement] Use model name as the node name in CLL

---

js/src/components/lineage/ActionControl.tsx
js/src/components/lineage/GraphColumnNode.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageViewContext.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/schema/ColumnNameCell.tsx
js/src/lib/hooks/useModelColumns.tsx

[Bug] Fix regression issue from auto lint

---

js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewContext.tsx

Bug
- Fix cll presentation when clicking column node

[Bug] Fix cll presentation when clicking column node

---

.github/workflows/integration-tests.yaml

Chore
- Cloud smoke test case contains deleting state file, so it cannot be tested concurrently right now.

[Chore] Add concurrency to cloud smoke test

---

recce/util/cll.py
tests/util/test_cll.py

Bug
- Fix inline derived table alias case
- Fix derived source from cte

[Bug] Fix inline derived table alias cll

---

js/app/page.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewNotification.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/lineage/SingleEnvironmentQueryView.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/SqlEditor.tsx
js/src/lib/api/sessionStorageKeys.ts
recce/cli.py

Feature
What's changed:
- message from CLI
- message from web page (lineage notification and query setup guide)
- modal to normal tab

[Feature] Update single env mode message and UI

---

recce/adapter/dbt_adapter/__init__.py

Feature
Include source column schema from the manifest
DRC-1143

[Feature] Include source columns schema from manifest

---

js/src/components/data-grid/ScreenshotDataGrid.tsx
js/src/components/profile/ProfileDiffResultView.tsx
js/src/components/profile/ToggleSwitch.tsx
js/src/components/query/QueryDiffResultView.tsx
js/src/components/query/querydiff.tsx
js/src/components/valuediff/ValueDiffDetailResultView.tsx
js/src/lib/api/profile.ts

Add the new "Inline" view of the profile diff
Feature

[Feature] Add new inline view for profile diff

---

js/src/components/lineage/NodeSqlView.tsx

UI enhance 
- Show model name on the Code Diff view
- Single env mode
- Diff mode

[Refine] DRC-1146 Show model name in Code Diff view

---

js/app/page.tsx
js/src/lib/api/version.ts
recce/__init__.py
recce/cli.py
recce/server.py

UX enhance
- The notification will be shown on both CLI console and web page.
- CLI notification
- Frontend notification 

[Feature] DRC-1105 Notify user Recce have a new version to update

---

js/eslint.config.mjs
js/src/components/app/Filename.tsx
js/src/components/app/StateExporter.tsx
js/src/components/app/StateImporter.tsx
js/src/components/charts/HistogramChart.tsx
js/src/components/check/CheckList.tsx
js/src/components/lineage/LineageView.tsx
js/src/lib/hooks/ScreenShot.tsx
js/src/lib/hooks/useModelColumns.tsx
js/src/utils/formatters.tsx

Chore
- Fix `@typescript-eslint/no-unsafe-function-type`
- Fix `@typescript-eslint/no-extra-non-null-assertion`
- Fix `@typescript-eslint/no-wrapper-object-types`
- Fix `@typescript-eslint/consistent-generic-constructors`
- Fix `@typescript-eslint/no-unnecessary-template-expression`
- Fix `@typescript-eslint/consistent-type-definitions`
- Fix `@typescript-eslint/no-non-null-assertion`
- Fix `@typescript-eslint/no-non-null-asserted-optional-chain`
- Fix `@typescript-eslint/no-unused-expressions`
- Fix `@typescript-eslint/restrict-template-expressions`, allow `number` values to be used in template expressions.
N/A
`CheckList.tsx`, …

chore: Fix Ten More lint configurations

---

js/src/components/query/querydiff.tsx
js/src/components/valuediff/valuediff.tsx

Before
After
Fix the color issue.

[Bug] Make the cell diff color consistent

---

js/app/page.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/onboarding-guide/Notification.tsx
js/src/components/profile/ProfileDiffResultView.tsx
js/src/components/query/QueryResultView.tsx
js/src/components/query/querydiff.tsx
js/src/components/run/RunResultPane.tsx
js/src/components/run/registry.ts
recce/adapter/dbt_adapter/__init__.py
recce/config.py
recce/models/types.py
recce/tasks/__init__.py
recce/tasks/profile.py
tests/tasks/test_profile.py

Feature
- Single environment can support profile selected model

[Feature] implement unlock profile diff

---

recce/adapter/dbt_adapter/__init__.py

Feature
- provide a class method `as_manifest` and add cache for it

[Feature] CLL loading time enhancement

---

.github/workflows/integration-tests-cloud.yaml
.github/workflows/integration-tests.yaml

Chore
- External contribution needs to access actions vars and secretes
- Add `paths-ignore`
- Because the action triggered with `pull_request_target` has full permission, so we should review the code before run the integration test.

[Chore] Fix the cloud smoke test failed in forked PR

---

recce/adapter/dbt_adapter/__init__.py

Bug
- columns in manifest is case-insensitive, we should use columns from catalog 

[Bug] Duplicated source column in snowflake

---

js/eslint.config.mjs
js/package.json
js/src/components/app/Filename.tsx
js/src/components/app/StateSynchronizer.tsx
js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckList.tsx
js/src/components/check/CheckPage.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/PresetCheckRecommendation.tsx
js/src/components/lineage/useMultiNodesAction.ts
js/src/components/onboarding-guide/OnboardingGuide.tsx
js/src/components/run/RunList.tsx
js/src/components/run/RunResultPane.tsx
js/src/lib/hooks/LineageGraphContext.tsx
js/src/lib/hooks/RecceActionContext.tsx
js/src/lib/hooks/useModelColumns.tsx
js/src/lib/hooks/useRun.tsx

Chore
- Update pnpm to latest
- Fix `@typescript-eslint/no-misused-promises` - 26 errors
- Fix `@typescript-eslint/no-floating-promises` - 49 errors
Fixes two eslint configuration rules regarding usages of promises
N/A
Details
- eslint.config.mjs
- Re-arrange rules - group and mark any typing rules
- LineageGraphContext.tsx
- LineageView.tsx
- OnboardingGuide.tsx
- Add void for now - don't affect function callstack
- CheckDetail.tsx
- CheckList.tsx
- CheckPage.tsx
- Filename.tsx
- LineageViewTopBar.tsx
- PresetCheckRecommendation.tsx
- RecceActionContext.tsx
- RunList.tsx
- RunResultPane.tsx
- StateSynchronizer.tsx
- …

chore: Fix Linting for Promises

---

recce/core.py

Fix
```
./recce/core.py:313:5: F824 `global recce_context` is unused: name is never assigned in scope
make: *** [flake8] Error 1
```
Chore

Fix flake8

---

js/app/page.tsx
js/src/components/app/Filename.tsx
js/src/components/app/StateExporter.tsx
js/src/components/app/StateImporter.tsx
js/src/components/check/CheckDescription.tsx
js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckList.tsx
js/src/components/check/CheckPage.tsx
js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/NodeTag.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/lineage/PresetCheckRecommendation.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/SqlEditor.tsx
js/src/components/run/RunList.tsx
js/src/components/run/RunResultPane.tsx
js/src/lib/api/cacheKeys.ts
js/src/lib/api/flag.ts
js/src/lib/api/instanceInfo.ts
js/src/lib/hooks/RecceContextProvider.tsx
js/src/lib/hooks/RecceInstanceContext.tsx
js/src/lib/hooks/RecceModeContext.tsx
js/src/lib/hooks/useRecceInstanceInfo.tsx
recce/adapter/dbt_adapter/__init__.py
recce/apis/run_func.py
recce/cli.py
recce/core.py
recce/server.py

Feature
- Recce read-only mode

[Feature] Recce read only mode

---

recce/core.py

Bug
- Fix aggregation excluding statement

[Bug] Fix run result aggregation

---

js/app/page.tsx
js/src/components/app/Filename.tsx
js/src/components/app/StateSharing.tsx
js/src/components/run/RunResultPane.tsx
js/src/lib/api/instanceInfo.ts
js/src/lib/api/state.ts
js/src/lib/hooks/RecceContextProvider.tsx
js/src/lib/hooks/RecceInstanceContext.tsx
js/src/lib/hooks/RecceShareStateContext.tsx
recce/cli.py
recce/server.py
recce/state.py
recce/util/recce_cloud.py

Feature
- It allows sharing the recce state from recce server UI

[Feature] Support Recce share from UI

---

js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx

The regression issue for the partial breaking change UI PR
Bug

[Bug] Fix clicking node not working issue

---

js/src/components/lineage/LineageView.tsx

[Enhancement] Dont open side pane if select a column node

---

.github/workflows/tests-python.yaml

Chore
- Update test-python setup python action version

[Chore] Update test python workflow action version

---

recce/util/breaking.py

Chore
- Fix flake8 issue (unused local variable)

[Chore] Fix legacy flake8 issue

---

js/src/components/lineage/lineage.ts

[Bug] The changed columns should not show in the CLL mode

---

recce/server.py

Bugfix
- auth_options could be None

[Fix] Failed to access api_token due to auth_options is None

---

js/.env.development
js/src/components/app/StateSharing.tsx
js/src/components/run/RunResultPane.tsx
js/src/lib/const.ts
recce/cli.py

Enhancement
- Refine UI language

[Feature] Refine UI language

---

recce/util/breaking.py
tests/util/test_breaking.py

it now shows changed columns even it is a breaking change. 

[Enhancement] Add changed columns even in breaking change models

---

recce/adapter/dbt_adapter/__init__.py

[Bug] Behavior wrong while open CLL in the breaking change nodes

---

js/app/page.tsx
js/src/components/app/Filename.tsx
js/src/components/app/StateSharing.tsx
js/src/components/run/RunResultPane.tsx
recce/cli.py

Feature change
- remove recce share feature lock
- hide recce share in single env mode
- hide recce share in read only mode
- wrap shared link

[Feature] Remove recce share restriction

---

js/eslint.config.mjs
js/package.json
js/pnpm-lock.yaml
js/src/components/lineage/LineageView.tsx
js/src/lib/api/types.ts
js/src/lib/const.ts

Chore
- Fix `@typescript-eslint/no-redundant-type-constituents`
- Fix `@typescript-eslint/require-await`
- Fix `@typescript-eslint/await-thenable`
- Fix `@typescript-eslint/no-confusing-void-expression`
- Update pnpm to latest version.
- Update linting packages to latest
- Note: Remaining lint issues will be fixed by properly typing the code
N/A
N/A
NONE

chore: Fix Unnecessary async/await usages

---

recce/adapter/dbt_adapter/__init__.py

[Bug] Fix unbounded variable error

---

README.md
js/app/page.tsx
js/src/components/app/StateSharing.tsx
js/src/components/lineage/BreakingChangeSwitch.tsx
js/src/components/lineage/ColumnLevelLineageControl.tsx
js/src/components/lineage/SandboxView.tsx
js/src/components/lineage/SingleEnvironmentQueryView.tsx
js/src/components/onboarding-guide/Notification.tsx
js/src/components/run/RunResultPane.tsx
recce/cli.py
recce/config.py
tests/data/config/recce.yml

Update wording
- Change all the link URLs to the Recce Docs site to the new URL `https://docs.datarecce.io`

[Update] DRC-1240 Update all the link URLs to new docs site

---

js/src/components/app/StateSharing.tsx
js/src/lib/api/track.ts

Chore
Add telemetry for start sharing
PLA-392
Add `share_state` events with `enable`, `create`, and `copy`.

Chroe/Add share_state Amplitude events

---

js/src/components/lineage/ColumnLevelLineageControl.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewContext.tsx
js/src/lib/api/lineagecheck.ts

Bug / Enhancement
1. The lineage check store breaking change status while adding the check DRC-1208
2. Fix the CLL problem in the linage check while it is in cll mode. DRC-1249

[Bug] add lineage diff to checklist doesnt reflect breaking

---

README.md

update readme to align the April product launch
- please help to update the 1st image as the screenshot of PR#46 with Recce v1.0. The image is in docs site.
Yes, but the April product release note will naturally cover this readme update.

update readme content

---

js/src/components/app/StateExporter.tsx
js/src/components/app/StateImporter.tsx
js/src/components/app/StateSharing.tsx
js/src/components/check/CheckDetail.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/run/RunResultPane.tsx
js/src/lib/api/track.ts

Chore
Adding telemetry events for copying results and state IO
DRC-1155

[Chore] Add telemetry to button clicks

---

js/src/components/app/Filename.tsx

Bug
- It fixed bug from nullish coalescing auto fix

[Bug] Show file name correctly

---

js/src/components/schema/ColumnNameCell.tsx
js/src/components/valuediff/ValueDiffResultView.tsx

Bug
- Disable action menu in column grid

[Bug] Disable the column actions in readonly mode

---

js/app/page.tsx
js/src/lib/api/instanceInfo.ts
js/src/lib/hooks/LineageGraphContext.tsx
js/src/lib/hooks/RecceInstanceContext.tsx
js/src/lib/hooks/useCountdownToast.tsx
recce/cli.py
recce/server.py

Feature
- Add option `--lifetime` for `server` and `read-only` command.
- Once the lifetime expires, the server will terminate itself.
- Show a countdown toast 60 seconds before the lifetime expires.

[Feature] DRC-1219 Show the lifetime of Recce Server

---

js/package.json
js/pnpm-lock.yaml
js/src/lib/api/track.ts

Chore
Implement Amplitude Session Replay
N/A
NONE

feat: Implement Session Replay monitoring

---

js/src/components/lineage/GraphColumnNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewContext.tsx
js/src/components/lineage/LineageViewContextMenu.tsx

Allows to run action on columns in changed or cll models.
1. Columns in changed mode (if breaking change analysis is enabled)
2. Columns in CLL
Feature
Allows user to take actions on lineage view.
DRC-1174
1. I use. the same context menu to show both model-level and column-level menu
2. Reduce the code from `LineageView.tsx` and move the context related to `LineageViewContextMenu.tsx`

[Feature] Allows use to perform actions against columns in the lineage view

---

js/src/components/lineage/LineageView.tsx
recce/apis/run_func.py
recce/tasks/query.py

[Chore] Don't show blank page if /api/select failed

---

js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageViewContextMenu.tsx
js/src/components/lineage/lineage.ts

Feature
✅  We already list modified columns through breaking change analysis
✅   We already display columns in the CLL (Column-Level Lineage)
🤔  But there hasn’t been a quick way to take action on those related columns — like profiling, value diffing, or querying them directly.
We can now query, profile, and value diff for columns in the CLL or CHANGED model. :rocket:
We now have a shortcut to:
⚡  Quickly investigate related columns
⚡ Profile and compare values on those columns
⚡ Value diff for those columns  to drill into the changed row
⚡ Template and run query diffs based on them

[Feature] allows use to perform actions on lineage node

---

js/src/components/lineage/LineageView.tsx

[Enhancement] Don't change the focus node while changing breaking change analysis

---

js/src/components/run/RunList.tsx
js/src/lib/api/instanceInfo.ts
js/src/lib/hooks/RecceInstanceContext.tsx
recce/server.py

Bug
In single env mode, we should not allow add to the checklist from Run List

[Bug] Remove add to checklist in single env

---

js/src/components/lineage/LineageViewContextMenu.tsx
js/src/lib/api/runs.ts
js/src/lib/hooks/RecceActionContext.tsx

[Chore] Add tracking event for submit run from CLL/breaking change analysis

---

js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/NodeView.tsx
js/src/constants/tooltipMessage.ts
js/src/utils/DropdownValuesInput.tsx
recce/adapter/dbt_adapter/__init__.py
recce/tasks/query.py
recce/tasks/valuediff.py
tests/adapter/dbt_adapter/test_dbt_adapter.py

Feature
This PR replaces the dbt-audit_helper macro with Jinja templates.
We use only a few macros, so we replace them to remove the dependency.
DRC-1268
- Remove checking dbt-audit-helper
- Remove checking dbt-audit-helper in test
- Replace original macro with Jinja templates in value-diff and query-diff
- Remove checking in Recce UI

[Feature] Replace dbt-audit-helper with Jinja template

---

js/app/global.css
js/app/layout.tsx
js/app/page.tsx
js/package.json
js/pnpm-lock.yaml
js/pnpm-workspace.yaml
js/src/components/app/EnvInfo.tsx
js/src/components/query/QueryPage.tsx
js/src/components/query/SqlEditor.tsx
js/tailwind.config.ts

Feature
DRC-989: improvement for showing base & current env info
- Show basic environment info in the toolbar
- Show environment info for base environments for each query pane for custom queries
- Update and implement tailwind so it actually works
- Add global.css file - standard for next.js and required for tailwind
- Add global.css to layout.tsx
- Update linting packages
- Fix location of @babel/helpers and @babel/runtime in the package.json file
- Add pnpm-workspace.yaml file
- Fix tailwind.config.ts file
- Basic environment information is now shown in the toolbar next to the …

feat: DRC-989 Improve Env Info

---

js/src/components/lineage/LineageViewTopBar.tsx
js/src/components/lineage/NodeView.tsx
js/src/components/schema/ColumnNameCell.tsx
js/src/constants/tooltipMessage.ts
recce/adapter/dbt_adapter/__init__.py
recce/tasks/profile.py
tests/adapter/dbt_adapter/test_dbt_adapter.py
tests/tasks/test_profile.py

Feature
Decouple dbt-profiler dependency by replacing the macro with a rebuilt Jinja template.
DRC-1274

[Feature] Replace dbt profiler with jinja template

---

recce/adapter/dbt_adapter/__init__.py
recce/util/breaking.py
recce/util/cll.py
tests/util/test_cll.py

New feature
This is the CLL enhancement features. 
Now when we parse a sql, we can understand
1. For all columns, the transformation type and upstream columns
2. (⭐  New) the upstream columns
This PR has not change the API and frontend.

[Feature] parse the model to column dependency

---

tests/util/test_breaking.py

[Chore] Add back to unused variable in the unittest

---

js/package.json
js/src/components/app/StateSharing.tsx
js/src/components/run/RunResultPane.tsx

- Redirect on unauthenticated to signin, then to relaunch page
Feature
User will always sees a share button
- Redirect on unauthenticated to signin, then to relaunch page
[DRC-1292](https://linear.app/recce/issue/DRC-1292/oss-user-sees-share-button-always)
NONE

[WAIT] feat: drc-1292 User always sees a share button

---

js/src/components/schema/ColumnNameCell.tsx
js/src/components/schema/SchemaView.tsx
js/src/components/schema/schema.tsx
js/src/components/schema/style.css

Feature
- Make the row of schema view clickable, and clicking can trigger column-level lineage view.
- Add row selection UI effect.
- Remove eye icon for column-level linage.

[Feature] Make the row of column clickable

---

js/app/page.tsx
js/src/components/AuthModal/AuthModal.tsx
js/src/lib/hooks/RecceContextProvider.tsx

Bugfix
Fixes issue with `AuthModal` to ensure it loads correctly when snoozed
drc-1335
NONE

bugfix: drc-1334

---

js/app/page.tsx

- Ensure Modal does not show up on demo site
HOTFIX
Ensure Auth Modal does not show up on demo site
DRC-1326
NONE

bugfix: DRC-1336

---

recce/util/cll.py
tests/util/test_cll.py

[Bug] the model to column does not support in and not in

---

js/src/components/lineage/GraphColumnNode.tsx
js/src/components/lineage/LineageView.tsx

It make the impact radius obvious when it is in CLL mode
Before
After
Enhancement

[Enhancement] Dont highlight the model if it is not in the impact radius

---

recce/adapter/dbt_adapter/__init__.py
recce/server.py
recce/util/lineage.py
tests/adapter/dbt_adapter/conftest.py
tests/adapter/dbt_adapter/test_dbt_cll.py

Feature
Add column filter to CLL api

[Feature] Filter the column and model dependencies in the CLL API

---

README.md

Chore
Fix Readme Recce icon image link
- before
- after

[Chore] Fix readme icon image link

---

recce/util/recce_cloud.py
tests/util/test_api_token.py

Feature
- Provide the information of oss user-id and version to Recce Cloud for tacking `Connect OSS to Cloud` event by request header
- Only provide those information when anonymous tracking is enabled

[Feature] DRC-1349 Track `Connect OSS to Cloud` event

---

recce/event/__init__.py
recce/util/api_token.py

feature
- Add ability (when tracking is enabled by the user) to see when the cloud api token is connected
drc-1348
NONE

feat: drc-1348

---

.github/workflows/nightly.yaml

Infra
Fix typo in nightly build workflow

[Fix] Fix typo in nightly build workflow

---

js/src/components/lineage/LineageView.tsx
js/src/components/lineage/lineage.ts
js/src/lib/api/cll.ts
recce/adapter/dbt_adapter/__init__.py
recce/models/types.py
recce/util/lineage.py
tests/adapter/dbt_adapter/test_dbt_cll.py

[Chore] Use new cll flatten api response format to generate cll graph

---

recce/adapter/dbt_adapter/__init__.py
recce/server.py
tests/adapter/dbt_adapter/test_dbt_cll.py

Feature
Add new impact radius API endpoint

[Feature] Add impact radius api endpoint

---

js/src/components/run/RunModal.tsx

feat: drc-1393

---

js/src/lib/api/flag.ts
recce/cli.py
recce/server.py
recce/util/api_token.py
recce/util/onboarding_state.py
recce/util/recce_cloud.py
tests/util/test_api_token.py
tests/util/test_onboarding_state.py

Feature
Clean up the process surrounding the onboarding state.
DRC-1338
NONE

feat: drc-1338

---

js/src/components/lineage/LineageView.tsx
js/src/lib/api/cll.ts
recce/adapter/dbt_adapter/__init__.py
recce/models/types.py
recce/server.py
recce/util/lineage.py
tests/adapter/dbt_adapter/test_dbt_cll.py

The new `/api/cll` has these params:
- node_id
- column_id
- change_analysis=true|false
- cll=true
- upstream=
- downstream=
Supported scenario
- impact radius: {downstream}
- Impact radius+: {change_analysis=true, downstream}
- (ms2) impact radius++: {change_analysis=true, cll=true, downstream}
- (ms1) model impact radius: {change_analysis=true, cll=true, node_id=<>, downstream}
- model upstream&downstream: {node_id=<>, downstream, upstream}
- column impact radius: {change_analysis=true, cll=true, node_id=<>, column_id=<>, downstream}
- column lineage: {change_analysis=true, cll=true, node_id=<>, column_id=<>, upstream, downstream}
This is partial implementation of impact radius, we will refine this api …

[Feature] API to support Impact radius for all changed nodes

---

recce/adapter/dbt_adapter/__init__.py
tests/adapter/dbt_adapter/test_dbt_cll.py
tests/test_core.py

[Feature] Add on demand change analysis to CLL parsing

---

js/src/components/AuthModal/AuthModal.tsx

BugFix
Fixes issue with skip button. User can now correctly use the skip and snooze buttons
DRC-1422
Skip button now works correctly in the "Use Recce Cloud" Modal

BugFix: drc-1422

---

js/src/components/lineage/ColumnLevelLineageControl.tsx
js/src/components/lineage/GraphColumnNode.tsx
js/src/components/lineage/GraphNode.tsx
js/src/components/lineage/LineageView.tsx
js/src/components/lineage/LineageViewContext.tsx

1. Add the back button
2. Change the UI for impact radius
3. Fix issue in the linage check

[Enhancement] followup issue for new impact radius

---

recce/cli.py

Bugfix
- Join project dir to the target and target-base path
- Fix issue #800 
DRC-1452

[Bugfix] Join project dir to target and target-base path

---

js/src/components/lineage/ColumnLevelLineageControl.tsx
js/src/components/lineage/LineageView.tsx

1. Remove back button
2. Add the Impact Radius button

[Enhancement] Impact radius: Remove back and separate the state and action

---

js/src/components/lineage/LineageView.tsx
recce/adapter/dbt_adapter/__init__.py
tests/adapter/dbt_adapter/test_dbt_cll.py

Show the added models in the impact radius, and show all columns in the model.

[Bug] impact radius should include the added nodes

---

recce/adapter/dbt_adapter/__init__.py
recce/util/cll.py
recce/util/perf_tracking.py

Feature
- Add performance telemetry to impact radius

[Feature] Add performance telemetry to impact radius

---

js/src/components/lineage/GraphNode.tsx

[Enhancement] Remove dashed border for non-breaking

---

recce/event/collector.py

[Bug] Fix UnboundLocalError

---

recce/util/recce_cloud.py

Bugfix
- Fix get upload share state presigned URL failed issue

[Fix] Convert all the metadata values to string

---

recce/cli.py

Bugfix
- Fix typo when read the `share-url` from ENV

[Fix] DRC-1495 typo when load the Share URL from ENV

---

js/src/components/lineage/LineageView.tsx

Bugfix
Fix copy lineage functionality #824 
DRC-1501

[Bugfix] copy lineage functionality

---

js/src/components/AuthModal/AuthModal.tsx
js/src/components/app/StateSharing.tsx
js/src/components/run/RunResultPane.tsx

Chore
Change the message of the Auth modal and enable sharing modal
- before
- after

[Chore] Update modals message

---

js/src/components/lineage/SeverDisconnectedModalContent.tsx
js/src/lib/hooks/LineageGraphContext.tsx
js/src/lib/hooks/RecceInstanceContext.tsx

Feature
Add modal content when the preview instance expires.

[Feature] Add modal for preview instance expiration

---

recce/server.py

Bug
In cloud mode, merge remote recce state file when the server shuts down.

[Bug] Merge the remote state file before server shutdown

---

js/.husky/pre-commit

BugFix
Ensure python `pre-commit` runs alongside husky
n/a
NONE

BugFix: Add python pre-commit to Husky

---

js/.husky/pre-commit

Chore
- precommit failed when committing both python and js at the same time

[Chore] Fix precommit when commit both python and js

---

js/src/components/valuediff/valuediff.tsx

Bug
- The column names of the query results from Snowflake are in uppercase, and the primary key in the query diff page should consider that when displayed.

[Bug] Consider case of column in value diff grid

---

js/package.json
js/pnpm-lock.yaml
js/src/utils/DropdownValuesInput.tsx

Feature Request
- Make primary key search case-insensitive
- Fix ESLint dependency issues
#852 

[Feature] DRC-1638 Make primary key search case-insensitive

---

.github/workflows/integration-tests-cloud.yaml

Chore
The cloud smoke test needs to specify the repo name if it's forked repo.

[Chore] Fix checkout action when it's fork repo

---

tests/util/test_lineage.py

Chore
Add missing unit tests for refactoring

[Chore] Add unit tests for lineage upstream downstream

---

recce/artifact.py
recce/cli.py
recce/state/cloud.py
recce/state/state_loader.py
recce/util/recce_cloud.py
tests/state/test_cloud.py
tests/state/test_state_loader.py

Feature
1. Support `recce snapshot --snapshot-id`
2. Support `recce server --cloud --snapshot-id <snapshot-id>
3. Reactor the `recce/state/cloud.py`. Seperate the load and export logics to `_load_state_from_xxx` and `_export_state_to_xxxx`
DRC-1641

[Feature] Support snapshot related cli commands

---

recce/tasks/rowcount.py
recce/tasks/schema.py

Chore
- For security patch, we need to support deepdiff v8

[Chore] Extend deepdiff compatibility to v8

---

setup.py

Security Patch
Patch the [CVE-2025-58367](https://github.com/advisories/GHSA-mw26-5g2v-hqw3)

[Patch] Upgrade `deepdiff` to the latest version

---

js/app/page.tsx

Bug
- Recce Server encounters client exception when there's a new recce release
DRC-1699

[Bug] Client exception when launching recce server

---

js/src/components/check/CheckDetail.tsx
js/src/components/check/CheckEmptyState.tsx
js/src/components/check/CheckPage.tsx

Feature
- Enhance the checklist page when there are no checks
- Reload the checklist when a check is deleted.
- before
- after

[Feature] Enhance checklist page with no checks

---

recce/adapter/dbt_adapter/__init__.py

Bug
- After dbt-databricks v1.9, `DatabricksColumn` was removed from package exports.

[Bug] Fix DatabricksColumn import after dbt-databricks 1.9

---

recce/summary.py

Bug
In summary, it outputs a PR page link.
The path is moved to `/classic` and should be deprecated soon.

[Bug] Fix pr page path in summary
