js/src/components/lineage/LineageView.tsx, js/src/components/lineage/lineage.test.ts, js/src/components/lineage/lineage.ts
Feature
- Default shows Changed Only mode 
- Add a new ControllButton `Switch View` on the ReactFlow controls
- Show current View Mode on the top-left of Lineage View
sc-32616
=> [Feature] sc-32616 Default show changed only nodes in Lineage View

js/src/components/lineage/LineageView.tsx, recce/cli.py, recce/dbt.py, recce/server.py, setup.py
Feature
- Monitor the manifest and catalog files changed
- Reload the dbt context once we detect `manifest.json` or `catalog.json` files changed
- User websocket to brocast all the clients browser to reload lineage graph if we detected files changed.
RC-50
=> [Feature] Reload manifest and catalog files when they changed

js/app/page.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/MismatchSummary.tsx, js/src/components/summary/ChangeSummary.tsx, js/src/components/summary/SchemaSummary.tsx, js/src/components/summary/SummaryView.tsx, js/src/lib/hooks/LineageGraphContext.tsx, js/src/lib/hooks/RecceContextProvider.tsx
Feature
- Add summary page to demo the layout of changed schemas summary
RC-48
=> [Feature] rc-48 implement the summary page to demo the summary layout

js/app/page.tsx, js/package.json, js/pnpm-lock.yaml, js/src/components/check/CheckBreadcrumb.tsx, js/src/components/check/CheckDetail.tsx, js/src/components/check/CheckPage.tsx, js/src/components/lineage/NodeView.tsx, js/src/components/query/QueryPage.tsx, js/src/lib/hooks/useHashLocation.ts, recce/apis/check_api.py
Change to use wouter for global routing.
The reason why we don't use next route is 
- We use static site generation (SSG)
- We only generate one page, which is served by python fastapi
- Using hash as location is more suitable for our case
=> use wouter to routing

js/src/components/lineage/GraphNode.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/NodeTag.tsx, js/src/components/lineage/NodeView.tsx, js/src/components/summary/SchemaSummary.tsx
Feature
- Add `Query Row Count` button on the Lineage View page
- When users click that button, we will query all the row counts of showing models individually.
- Refactor row count tag component
RC-87
=> [Feature] RC-87 add a query row count button in lineage view

js/src/components/check/QueryDiffView.tsx, js/src/components/query/QueryDiffDataGrid.tsx, js/src/components/query/QueryPage.tsx, js/src/components/query/querydiff.test.ts, js/src/components/query/querydiff.tsx, js/src/components/query/styles.css, js/src/lib/api/adhocQuery.ts, recce/tasks/query.py
In the query diff view, we support to show only the changed one.
- We add the “Changed only” toggle, the default value is false, because if it set to true, we cannot select the primary key.
- Add the color of added/removed columns
- Add the color of added/removed rows (according to the PK settings)
- Change the color of cell value changed.
- Move the “Add to check” to be close to the query result.
=> [Feature] Query diff view allows to filter out unchanged rows or columns

recce/dbt.py, tests/test_sql_generator.py
Fix #171 
The root cause is that we use fake "model" node to generate the sql. However, it's not allowed to depends another private model. 
The solution is to use the SqlNode, which is used in `dbt show` and `dbt compile`
Bug
#171
=> [Bug] Fix the private model query issue

js/src/components/check/CheckDetail.tsx, js/src/components/check/CheckListLoader.tsx, js/src/components/lineage/ActionTag.tsx, js/src/components/lineage/GraphNode.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/NodeRunView.tsx, js/src/components/lineage/NodeSelector.tsx, js/src/components/lineage/NodeTag.tsx, js/src/components/lineage/NodeView.tsx, js/src/components/lineage/lineage.ts, js/src/components/rowcount/RowCountDiffResultView.tsx, js/src/components/rowcount/delta.ts, js/src/components/summary/SchemaSummary.tsx, js/src/lib/api/cacheKeys.ts, js/src/lib/api/models.ts, js/src/lib/api/runs.ts, js/src/lib/hooks/LineageGraphContext.tsx, recce/apis/run_api.py, recce/apis/run_func.py, recce/dbt.py, recce/tasks/rowcount.py, tests/apis/row_count_diff.json, tests/apis/test_run_func.py
The row count result would be materialized from all the previous row count runs.
Before
- When the browser restart, the row count information is lost.
Now
- The browser reload the row count information is still available
- If load from a recce state file, it will present the last row count queried by this state file.
In the lineage view, it shows the row count diff icon 
=> Materialize the last run result for row count diff

js/app/page.tsx, js/src/components/check/CheckPage.tsx, js/src/components/check/SchemaDiffView.tsx, js/src/components/histogram/HistogramDiffForm.tsx, js/src/components/lineage/GraphNode.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/NodeTag.tsx, js/src/components/lineage/graph.ts, js/src/components/lineage/lineage.test.ts, js/src/components/lineage/lineage.ts, js/src/components/schema/SchemaView.tsx, js/src/components/summary/ChangeSummary.tsx, js/src/components/summary/SchemaSummary.tsx, js/src/components/summary/SummaryView.tsx, js/src/components/top-k/TopKDiffForm.tsx, js/src/components/valuediff/ValueDiffForm.tsx, js/src/lib/hooks/LineageGraphContext.tsx, js/src/lib/hooks/RecceContextProvider.tsx
Because we may have different way to show the subset of nodes in the LineageView component, it does not make sense to keep the changed only and all. So
1. Only keep one linage graph, which is the fetched version.
2. The consumer of the LineageGraph should clone and filtered to their own and transform the the format ReactFlow uses.
Refactory
=> [Chore] Refactor LineageGraph interface

js/src/components/lineage/LineageView.tsx, js/src/lib/hooks/LineageGraphContext.tsx
Show refetch information if recce server is down
=> [Enhancement] Show refetch information if recce server is down

js/src/components/lineage/LineageView.tsx, js/src/components/lineage/styles.css, js/src/components/query/styles.css, js/src/lib/hooks/ScreenShot.tsx
Bugfix
- Fix the issue when copying the lineage graph. Some of the edges will disappear
- When copy the lineage graph image, change to use `html-to-image` library instead of using `html2canvas`
***Before***
***After***
***Ref***
https://github.com/xyflow/xyflow/issues/2118
DRC-260
=> [Bug] DRC-260 Fix linage view edges will disapper in copy image

js/src/components/check/CheckPage.tsx
Remove "create a simple check" icon.
DRC-269
=> [Enhancement] DRC-269 Remove "create a simple check" icon

recce/cli.py, recce/dbt.py, recce/run.py
Improve
-  run only the modified table model (including table and materialized)
- add the query time for the row count diff
Fix
- the state file is loaded if the file `recce_state.json` exists. It will let the keep the previous run results.
=> [Enhancement] Recce run: Only run the row count diff on table models

js/src/components/charts/TopKSummaryList.tsx, recce/dbt.py, recce/tasks/top_k.py
Fix #252 
In the bigquery, it does not support `unnest`
Solution:
Change to use JOIN on two sides and order by the counts of current enviornemtn
Note:
The reason why we use `__null__` in the CTE is because the outer join would not join the key is NULL for both side. So we use `__null__` to work around it.
https://stackoverflow.com/questions/72917878/snowflake-handling-of-nulls-in-a-join
Bug
=> [Bug] unable to run top k diff due to bigquery error

js/app/page.tsx, js/src/components/check/StateExporter.tsx, js/src/components/check/StateImporter.tsx, js/src/components/check/StateLoader.tsx, js/src/lib/api/state.ts, recce/models/state.py, recce/server.py
Feature
- Change state export and import behavior from overwriting to merging.
DRC-332
=> [Feature] Change the behavior of state loading and exporting

recce/server.py
Use the Pathlib library to ensure dbt artifact changes are detectable on Windows.
NONE
=> [Bug] DRC-316 Artifact server observer does not work in windows

recce/core.py, recce/server.py
The root endpoint is cached. So the client and server code is not in sync.
Disable cache for the root endpoint
=> [Bug] API endpoint /api/lineage not found

recce/cli.py, recce/summary.py
[Fix] remove typo
Fix
Fix the wording of the result of recce summary based on the feedbacks from team members.
=> [Fix] DRC-431 Fix recce summary wording

recce/adapter/dbt_adapter/__init__.py, recce/summary.py
Fix #336 
Root cause
The node type 'snapshot' is not handled correctly.
Solution
When building the lineage graph object, dont put the the excluded node to the `parent_map` dict
Bug
=> [Bug] The recce summary would raise exception if node is excluded

recce/pull_request.py, tests/test_pull_request.py
Run `recce run --cloud` in the github action, we cannot get the github pr information succesfully
=> [Bug] Should get the repository name from the ci event object

js/src/components/lineage/lineage.ts, recce/adapter/dbt_adapter/__init__.py
Bugfix
Build the node based on dbt manifest's `nodes` instead of `parent_map`
#344 
=> [Fix] DRC-511 build the nodes by `nodes` instead of `parent_map`

recce/adapter/dbt_adapter/__init__.py
In the recce server review, it should not be necessary to run `dbt deps` beforehand. Because the macros should from the manifests in the state file.
```
recce server --review <state_file>
```
Bug
=> [Bug] The dbt deps should not be required in the review mode

js/src/components/lineage/NodeView.tsx, recce/adapter/dbt_adapter/__init__.py, recce/tasks/rowcount.py, tests/adapter/dbt_adapter/dbt_test_helper.py, tests/adapter/dbt_adapter/test_selector.py
Feature
- support `select` and `exclude` params in `recce.yml`
DRC-508
NONE
=> [Feature] Support node selector in row count checks

js/src/components/check/CheckDescription.tsx, js/src/components/check/CheckDetail.tsx, js/src/components/check/CheckList.tsx, js/src/components/check/CheckPage.tsx, js/src/components/check/SchemaDiffView.tsx, js/src/components/lineage/GraphNode.tsx, js/src/components/query/QueryResultView.tsx, js/src/components/query/querydiff.tsx, js/src/components/schema/schemaDiff.ts, js/src/components/valuediff/ValueDiffResultView.tsx, js/src/lib/api/select.ts
Support the schema diff by dbt selector. Currently, it can only be added in the preset check. 
```yaml
checks:
- name: Schema diff (modified+)
type: schema_diff
params:
select: 'state:modified+'
- name: Schema diff (modified+, exclude snapshot)
type: schema_diff
params:
select: 'state:modified+'      
exclude: 'resource_type:snapshot'
- name: Schema diff for all nodes
type: schema_diff
params:
- name: schema by node id
type: schema_diff
params:
node_id: model.jaffle_shop.orders
```
Feature
=> [Feature] Support node selector in schema check

recce/cli.py
Bugfix
When executing `recce summary` outside the DBT project folder, the Recce will throw the error message `No dbt_project.yml.` However, the recce summary doesn't provide any options to let users assign the DBT project directory.
- Add dbt-related options in the `recce summary` command. 
#372 
=> [Fix] DRC-535 Add dbt related options in `summary` command

recce/apis/check_api.py, recce/apis/run_api.py, recce/event/__init__.py, recce/event/collector.py, recce/run.py, recce/server.py
Telemtry for two new events
- `api_event`: it would contain the api endpoint name and params. Currently, we have two endpoint `create_run`, `create_check`, `rerun_check`
- `load_state`: it would contains the `command`, `preset_checks`, and `checks`
=> Add telemetry for creating check/run and number preset check

recce/adapter/dbt_adapter/__init__.py, tests/adapter/dbt_adapter/dbt_test_helper.py, tests/adapter/dbt_adapter/test_selector.py
If there is disabled model with test, the manifest would cotains `.disable[<node_id>]`. The value is a list rather than a dict, it would cause this issue.
#384 
=> [Bug] AttributeError: 'list' object has no attribute 'from_dict'

recce/run.py
Bug
- In cloud mode, recce run should not load preset checks when the recce state was given.
DRC-578
NONE
=> [Bug] Fix recce run behavior by checking state existence

recce/server.py
Bugfix
- When the 3rd party procress try to update the manifest files, the file updated event could be triggered before the manifest file is updated completely.
- Check the json format before refresh the manifest files. If the file content is not valid json, skip the event and wait until the next updated event.
=> [Bug] DRC-577 Handle the updated artifact file is not updated completely

recce/adapter/dbt_adapter/__init__.py
Fix [405](https://github.com/DataRecce/recce/issues/405)
On new dbt 1.8 version there is error  LookupError: <ContextVar name='DBT_INVOCATION_CONTEXT_VAR' at 0x10c4889f0>   when using function "Run query" or "Run diff". This happens because class DbtAdapter sets the invocation context with function set_invocation_context({}) when dbt version is 1.8, but on tasks/query.py file the default_context is regenererated before calling function generate_sql from DbtAdapter.
To fix this, added a new call of set_invocation_context({}) on start of function generate_sql if dbt version is greater or equal than 1.8.
Bug fix
Added a new call of set_invocation_context({}) on start of function generate_sql if dbt version …
=> Resetting invocation_context on generate_sql function when dbt_version > 1.8

recce/summary.py
bug
- In summary, `Mismatched Nodes` should show mismatched only (e.g., when apply node selection)
DRC-589
NONE
=> [Bug] recce summary mismatched column show mismatched only

js/app/page.tsx, js/src/components/check/StateSynchronizer.tsx, js/src/lib/api/info.ts, js/src/lib/api/state.ts, js/src/lib/hooks/LineageGraphContext.tsx, recce/adapter/base.py, recce/adapter/dbt_adapter/__init__.py, recce/apis/check_api.py, recce/apis/check_func.py, recce/cli.py, recce/core.py, recce/models/check.py, recce/models/run.py, recce/models/types.py, recce/run.py, recce/server.py, recce/state.py, recce/util/recce_cloud.py, tests/adapter/dbt_adapter/dbt_test_helper.py, tests/test_state.py, tox.ini
When running recce server in the cloud mode, the syncing behavior is
1. When launching, it load the state from the cloud
2. When editing check, it upload(overwrite) state to the cloud
3. When clicking check, it download(import) runs and checks from the cloud. 
4. When termingating, it upload(overwrite) state to the cloud
However, there is a case we did not cover.
When run the recce server in the cloud mode. If the ci trigger the `recce run --cloud` and update the dbt artifacts to the code.  There is no way to sync the dbt artifacts in the recce server
In this PR, we implement the merge operation. In the 2,3,4 case, it changes to merge instance of one-way upload/download. Instead, it download the state(if necessary), merge the state, and upload back to the cloud.
In addition, if user click …
=> [Enhancement] support merge local and cloud state

js/src/components/run/RunModal.tsx, recce/tasks/profile.py
Fix #415 
1. Use separate sql for bigquery arrray. We show the min/max/avg/median of the the [ARRAY_LENGTH](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#array_length) of the array column
2. Show correct error message if there is any error from the profiling.
3. In the frontend, should show Rerun button if profile failed.
=> Profile diff should support bigquery array type

js/app/page.tsx, js/src/components/check/LineageDiffView.tsx, js/src/components/lineage/LineagePage.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/NodeFilter.tsx, js/src/components/lineage/NodeTag.tsx, js/src/components/lineage/NodeView.tsx, js/src/components/run/LatestRunPage.tsx, js/src/components/run/RunModal.tsx, js/src/components/run/RunResultPane.tsx, js/src/components/run/RunView.tsx, js/src/lib/hooks/RecceActionContext.tsx, js/src/lib/hooks/useRun.tsx, recce/tasks/valuediff.py
The new UI to show the run results under the lineage page
Feature 
=> [Feature] show run results under lineage

recce/state.py
Fix: cannot launch recce server in file mode if the file does not exist.
```
recce server myfile.json
```
Bug
=> [Bug] Cannot launch recce server in file mode when file does not exist

js/src/components/histogram/HistogramDiffForm.tsx, js/src/components/schema/ColumnNameCell.tsx, js/src/components/schema/SchemaView.tsx, js/src/components/schema/schema.tsx
There are too many steps to navigate a node to run histogram/topk diff
1. click the “Explore Changes” button
2. Select histogram
3. Find the column i want to run
4. Click Execute button
Provide additional ‘…’ button on the column name,  The steps would be
1. Scroll to the column
2. Click the “…” button
3. Select the “Historam” (or Top-K”
Feature
=> [Feature] Allows to show histogram and top k in the schema column

js/app/page.tsx, js/src/components/onboarding-guide/OnboardingGuide.tsx, js/src/lib/api/flag.ts, recce/cli.py, recce/core.py, recce/server.py, recce/state.py, recce/util/recce_cloud.py, tests/test_cli.py
Feature
- The onboarding guide will be shown based on the cloud user's `onboarding_state` when executing the' server' command with cloud mode. 
- Once user close the onboarding guide, will mark the cloud user's `onboarding_state` as `completed` 
=> [Feature] DRC-724 Save onboarding state and sync with cloud

js/src/components/lineage/LineageView.tsx
1. When clicking a node, center the node only when the side pane is not shown
2. Center the selected node while resizing if one node is selected
3. Fit the lineage graph while no node is selected.
=> [Enhancement] Update the centering and fitting logic in the lineage view

recce/tasks/histogram.py, tests/tasks/test_histogram.py
Fix #459 
If there is no min/max value for both side, the histogram would show 
```
in execute max_value = max(max_value, min_max_curr[0][1]) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```
This PR fix this issue and add corresponding unittest
Bug
#459 
=> [Bug] Fix histogram diff error if there is no min/max in the both side

recce/apis/run_func.py
If the run type is value diff detail, we should show correct run type name
=> [Bug] Fix the naming of the value diff detail

js/src/components/check/CheckDetail.tsx, js/src/components/run/RunResultPane.tsx, js/src/components/run/RunView.tsx, js/src/lib/hooks/useRun.tsx, recce/apis/check_api.py
1. Go to check
2. Click "Rerun" button to rerun a check. The check should be a job more than 10sec.
3. switch to other check and switch back
4. It would not show the submitted run.
Show the rerun run
Show the latest run before rerun.
=> [Bug] Should update to the latest run after rerun a check

recce/core.py, recce/run.py
Bug
- show pr information in recce server cloud mode
drc-857
NONE
=> [Bug] Export pr info from state loader in non-review mode

js/src/components/run/RunList.tsx, js/src/components/run/RunStatusAndDate.tsx
=> [Enhancement] Show date segment in the history list

recce/tasks/dataframe.py
Bugfix
- The average value will be Decimal type when executing the profile diff. When the value is Decimal('NaN'), it will cause the fastAPI's jsno encoder to fail. To prevent this edge case, convert it to float('NaN') as a workaround before the FastAPI fix this issue.
#476 
=> [Bug] DRC-883 Workaround when the query result is Decimal(NaN)

js/src/components/lineage/useValueDiffAlertDialog.tsx
Just remove the warning messaage 
From
to
Please see DRC-926 for detail
=> Remove the warning message

js/src/components/check/CheckDetail.tsx, js/src/components/check/CheckList.tsx, js/src/lib/hooks/useCheckToast.tsx
- Rollback to use `Mark as Checked` by `Mark as Approved`
- Rename all the naming of related-functions in checklist page
Fix wording
- Rollback to use `Mark as approved` instead of `Mark as checked` 
- Change related-functions in the source code of checklist page
- Change the wording in the popup warning
=> [Feature] DRC-925 Fix wording issues of checklist page

js/src/components/lineage/GraphNode.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/lineage.ts
1. Show context menu before click 1-node
1. Support select parent, child, all downstream, all upstream nodes
1. Disable the highlighting effect when hovering on a node.
1. Fix the distance of right click position and context menu
Feature
=> [Enhacnemtn] simplify right click menu by removing initial node selection

recce/adapter/dbt_adapter/__init__.py
Bug
- execute `get_columns_in_relation` macro in databricks didn't work
DRC-945
- the workaround refers databricks adapter 1.8
- it works with dbt 1.7 and 1.8
NONE
=> [Bug] Add extra process in get_columns for databricks

recce/run.py
Bugfix
- Change to use `get_lineage` instead of `get_model` as the source to judge
whether the schema diff has changed.
- When the data source is Snowflake, `get_model` method will trigger the DB
connection. In this case, we don't need to connect to DB. The manifest
file already contains all the information we need.
- Only `recce run` will trigger preset check pre-approved logic. This logic won't be invoked when launching the server.
=> [Bug] DRC-951 dbt run defer could make the server cannot launch

js/src/components/check/CheckDescription.tsx, js/src/components/check/CheckDetail.tsx
If the description is too long, the text should wrap instead of scroll.
In this PR, we also support to use cmd+enter to update the description.
=> [Bug] Text in checklist description is not easy to read

.github/workflows/integration-tests.yaml, integration_tests/dbt/smoke_test.sh, integration_tests/dbt/smoke_test_cloud.sh, recce/git.py
- Chore
- Add smoke test for Recce cloud version
- It's base on the example jaffle_shop_duckdb [PR#41](https://github.com/DataRecce/jaffle_shop_duckdb/pull/41) 
DRC-952
NONE
=> [Chore] Add smoke test for cloud mode

js/src/components/lineage/NodeView.tsx, js/src/components/lineage/PreviewChangeView.tsx, js/src/lib/api/track.ts, js/src/lib/hooks/useFeedbackCollectionToast.tsx
Feature
- Add telemetry for the experiment feature, preview change.
DRC-971
NONE
=> [Feature] Add telemetry for preview change

recce/event/collector.py
Bugfix
ZoneInfo is not supported in Python 3.8.
To remain Recce support Python 3.8, we replace the ZoneInfo with datetime.timezone.
#557 
DRC-991
=> Replace ZoneInfo with datetime.timezone

recce/adapter/base.py, recce/adapter/dbt_adapter/__init__.py, recce/cli.py, tests/test_cli.py
Feature
- Allow `recce server` to launch without `target-base` folder
- Show a warning message if the `target-base` folder not provide
- Enable `onboarding-mode` as True in server API `/api/flag` if the server launch without `target-base` folder
- Add unit-test for this case
=> [Fix] DRC-979 Allow Recce Server to launch without target-base

js/src/components/lineage/LineageViewTopBar.tsx
Feature
- Add Tooltip on node selector input field
- This tooltip will only shown under the single environment mode
=> [Feature] DRC-980 Show tooltip on node selector input field

js/src/components/lineage/PreviewChangeView.tsx, js/src/lib/api/localStorageKeys.ts, js/src/lib/hooks/useFeedbackCollectionToast.tsx, js/src/lib/hooks/useGuideToast.tsx
Feature
- After preview change success, hint user to prepare base env.
DRC-983
NONE
=> [Feature] Guide users to download artifacts to target base

recce/server.py
Feature
- Disable cache when access static file of the home page
- use `no-store` to skip `If-None-Match` and `If-Modified-Since` check
DRC-995
NONE
=> [Feature] Disable static file cache when access recce homepage

js/src/components/lineage/PresetCheckRecommendation.tsx, js/src/lib/api/sessionStorageKeys.ts, js/src/lib/api/track.ts
Feature
- To track the usage of the preset check recommendation and see if it is useful.
DRC-1024
NONE
=> [Feature] Telemetry for preset check recommendation

js/src/components/valuediff/ValueDiffResultView.tsx
Chore
The action menu in the value diff result view is hard to use when there are fewer results.
We simplify the actions from 2 to 1 and replace them with an icon button to open the value diff detail form.
DRC-996
=> [Chore] Replace Menu with IconButton in Value Diff Result View

.flake8, js/src/components/lineage/GraphNode.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/LineageViewContext.tsx, js/src/components/lineage/lineage.ts, js/src/lib/api/info.ts, js/src/lib/hooks/LineageGraphContext.tsx, recce/adapter/base.py, recce/adapter/dbt_adapter/__init__.py, recce/adapter/dbt_adapter/breaking.py, recce/core.py, recce/models/types.py, recce/server.py, recce/util/breaking.py, setup.py, tests/adapter/dbt_adapter/dbt_test_helper.py, tests/adapter/dbt_adapter/test_selector.py, tests/tasks/test_row_count.py, tests/test_core.py, tests/util/test_breaking.py
This PR support he breaking change analysis.
For modified nodes, it will use raw(templated) sql code. A node would mark as non-breaking change if
1. The sql sementic tree is identical
2. Or only new column added
Otherwise, it would mark as breaking change.
For non-breaking change, it will not mark the downstream as impacted. See the screenshot
=> [Feature]support breaking change analysis

js/src/components/lineage/LineageView.tsx, js/src/lib/api/checks.ts, js/src/lib/api/runs.ts, js/src/lib/api/track.ts, recce/apis/check_api.py, recce/apis/run_api.py
Chore
Add telemetry events. We would like to track the usage for the breaking change analysis feature. The question to ask
- How many active users enable this feature
- How many(percentage) users create run when breaking change analysis is enabled
- How many(percentage) users create check when breaking change analysis is enabled
FrontEnd
Event type: `[Experiment] breaking_change_analysis`
```js
{
'enabled': true
}
```
**Backend**
Event type: `api_event` (existing)
```js
{
'action': 'create_run',
'track_props': {
'breaking_change_analysis': true
}
}
```
```js
{
'action': 'create_check',
'track_props': {
'breaking_change_analysis': true
}
}
```
**Special notes for your …
=> Add telemetry event for breaking change analysis

js/src/components/histogram/HistogramDiffForm.tsx, recce/tasks/histogram.py, tests/tasks/test_histogram.py
Bugfix
- Histogram should not support string type with dynamic length. Ex varchar(16), etc...
=> [Fix] DRC-1062 Fix histogram supported type filter

recce/adapter/dbt_adapter/__init__.py
Feature
To capture the original manifest as the base when launching recce server in the single env mode.
After rebuilding a model, it can show the lineage diff.
DRC-1065
NONE
=> [Feature] Capture the original manifest as base in single env

js/app/page.tsx, js/src/components/check/CheckPage.tsx, js/src/components/lineage/LineageView.tsx, js/src/lib/hooks/RecceActionContext.tsx, js/src/lib/hooks/RecceCheckContext.tsx, js/src/lib/hooks/RecceContextProvider.tsx
Improve UX
- Memorize the latest check item from the Checklist tab. We will remember the previous index when switching back to the Checklist tab.
- Auto-select the related Lineage Node when the run action is triggered from the check result. (Ex. Show mismatched values...). Select history runs will also apply this logic.
- If the selected node is not included in `changed_models` mode, the lineage view will auto-switch to `all` mode.
- When selecting a node in Lineage View, the flow graph will autofocus to the selected node.
=> [Feature] DRC-998 Improve the ux when user back and forth checklist tab

js/src/components/lineage/LineageView.tsx
Bugfix
- Skip auto focus logic when the run type is `query`, `query_diff` or `row_count`
- Execute `Run Query` won't break the `Sandbox` or `Single Env Query` Modal
=> [Fix] DRC-1092 Skip auto-focus logic when some specific run types

recce/cli.py, recce/state.py
Bugfix
- Check `password` when uploading/downloading the recce state file in Recce Cloud
- Refactor class `RecceCloudStateManager` to add `verify` method and store the error and hint messages.
- Extract the cloud-related error message as global variables
=> [Fix] DRC-1127 Check password option when upload/download state file

js/.eslintrc.json, js/.prettierrc, js/eslint.config.mjs, js/package.json, js/pnpm-lock.yaml, js/tsconfig.json
Chore: Update Eslint and Prettier to the latest
Currently - eslint and prettier is not fully configured. This PR enables the latest eslint and prettier, along with standard plugins for Next, Tailwind, and Typescript. 
The PR does **not** fix any lint issues, however it does annotate `43` standard lint configurations with warnings, and they should be addressed in the future. As of now, this is the output of running `pnpm lint`:
```bash
✖ 2183 problems (0 errors, 2183 warnings)
0 errors and 1164 warnings potentially fixable with the `--fix` option.
```
N/A
- Update eslint to latest version 9.
- Remove .prettierrc and .eslintrc.json …
=> chore: Update eslint to version 9

js/app/page.tsx, js/eslint.config.mjs, js/src/components/app/EnvInfo.tsx, js/src/components/errorboundary/ErrorBoundary.tsx, js/src/components/lineage/lineage.test.ts, js/src/components/lineage/lineage.ts, js/src/components/query/QueryDiffResultView.tsx, js/src/components/run/RunView.tsx, js/src/components/schema/SqlDiffView.tsx, js/theme/components/Checkbox.ts
Chore
This PR continues to fixe eslint configurations - fixing seven more.
N/A
- Fix react/no-unknown-property
- Fix @typescript-eslint/array-type
- Fix @typescript-eslint/no-deprecated
- Fix @typescript-eslint/dot-notation
- Fix @typescript-eslint/unbound-method
- Fix @typescript-eslint/no-unnecessary-type-parameters
- Fix @typescript-eslint/prefer-optional-chain
Fix test expect() lines that were not running
Disable a few unbound-method checks
Add TODO regarding typing inconsistency for `LineageData` Fix `prefer-optional-chain` in QueryDiffResultView.tsx: `value != null` is a preferred way to test if a value is either null or …
=> chore: Fix more linting issues, remove (default is error)

recce/adapter/dbt_adapter/__init__.py
Fix #655 
Sometimes, we cannot compile sql for some reason. (different var, envvar from the dbt run), we should not break the initiating process but left it as parse error.
Bug, Hotfix
#655
=> [Bug] Dont break the loading logic if parsing cll error

recce/adapter/base.py
Bugfix
Fix the typo in NodeDiff parameter name causes 500 error
#670 
=> [Bug] Typo in NodeDiff parameter name causes 500 error

js/src/components/lineage/GraphNode.tsx, js/src/components/lineage/LineageView.tsx, js/src/components/lineage/LineageViewContext.tsx, js/src/components/schema/ColumnNameCell.tsx
1. change the select mode `"single"` to `undefined`
2. change the select mode `multi` to `selecting`
3. change the name `selectNodeMulti` to `select`
4. Add the `cursor: 'pointer'`  to the node checkbox
5. Move all the rendering code together.
Chore
=> [Chore] Refine the select mode in the LineageView

recce/util/breaking.py, tests/util/test_breaking.py
This PR enhance original breaking change analysis feature. Now, it category the changed model to three categories:
- **Breaking change**: All downstream of the model is affected. Change the number of rows. 
- **Partial breaking change**: Only affect the downstream which use certain columns. The row count of this model is not changed.
- **Non breaking change**: No change or only new column added. 
=> Support to analyze the partial breaking change.

js/app/page.tsx, js/src/components/app/Filename.tsx, js/src/components/query/QueryPage.tsx, js/src/lib/api/info.ts, js/src/lib/hooks/LineageGraphContext.tsx, recce/server.py
Feature
- In read-only mode, add the state generated time in the file name title.
- Add message to query page in read-only mode.
=> [Feature] Add notifications to read-only mode

recce/adapter/dbt_adapter/__init__.py
Fix #717 
Bug
In dbt 1.9, the `state:modifed` method would check the contract and it requires `adapter`. But in current flow, the adapter could not be found in the `select_nodes` path.
=> [Bug] Modified of contract would fail the node selection

recce/tasks/profile.py
1. Run profile difff
2. Select only the added columns
3. It would show empty result.
=> [Bug] Profile diff result is empty if profile on only added columns

js/src/components/lineage/LineageView.tsx, js/src/components/lineage/LineageViewContextMenu.tsx
Steps
1. Open this history
2. Right click on a node
The context menu is popped up with wrong offset.
=> [Bug] The context menu would have offset if the history pane is open

js/src/components/lineage/SeverDisconnectedModalContent.tsx, js/src/lib/api/instanceInfo.ts, js/src/lib/hooks/LineageGraphContext.tsx, recce/cli.py, recce/server.py
Feature
- Show the `restart` button when the Share Instance has expired
- The `share_url` will be provided by EnvVar `RECCE_SHARE_URL` when execute `read-only` command
=> [Feature] DRC-1272 Show restart button when the end of share instance

recce/cli.py, recce/event/__init__.py, recce/util/api_token.py, recce/util/recce_cloud.py, tests/util/test_api_token.py
Feature
- Update the option description of `--cloud-token` specific for GitHub
- Verify the api-token with Recce Cloud when it's provided by option
- Store the user provied api-token to recce user profile if it's valided
- Update user's onboarding_state to `installed` when user provided api-token
=> [Feature] Mark onboarding state as `installed` when api-token is set

js/app/page.tsx, js/src/components/app/EnvInfo.tsx
Bug
- UI broken when browser window is resized to a certain width.
before:
after: add height limitation and responsive display (to see the manifest timestamp, users need to click info icon)
=> [Bug] UI checklist badge broken when page resize

recce/cli.py, recce/core.py
Chore
1. Update wording for `recce debug` and launching single env mode
2. Fix logic while launching Recce with no folder for the current env
PLA-458
- `recce debug` without base
- `recce debug` all set
- `recce server` without current
- `recce server` in single mode
=> [chore] Update wording for single environment mode

.github/workflows/nightly.yaml
Infra
- We can manually trigger nightly build.
- When the new version of nightly conflict with the existing version, add `-postN` as a post-release build
=> [Feature] DRC-1285 Manually trigge action could release official nightly

recce/adapter/dbt_adapter/__init__.py
Fixes #826
Bug
In dbt 1.9, it supports [new flag to prevent False Positives](https://docs.getdbt.com/reference/node-selection/state-comparison-caveats#false-positives) in the `state:modified` result.
#826 
=> Fix State Selection does not work as expected for row_count_diff

recce/util/lineage.py
⏱️ Runtime :   **`10.8 milliseconds`**  **→** **`3.24 milliseconds`** (best of `532` runs)
The optimization replaces recursive DFS with iterative DFS using an explicit stack, delivering a **233% speedup** by eliminating Python's function call overhead.
**Key changes:**
- **Eliminated recursion**: Replaced nested `dfs()` functions with `while` loops using explicit stacks
- **Reduced function calls**: The line profiler shows the original code spent 99.8% of time in `dfs()` calls, which are now eliminated
- **Added duplicate prevention**: Added `if parent not in upstream` checks to avoid redundant stack operations
**Why it's faster:**
- **Function call overhead elimination**: Python function calls are expensive due to frame creation, local scope management, and argument passing
- **Better …
=> ⚡️ Speed up function `find_column_dependencies` by 233%
